---
permalink: windows/concept-cloning-database-backup.html 
sidebar: sidebar 
keywords: clone, database, task, test, upgrade, affect, production, duplicate, master, installation, train, system, duplicate, master, base, server, requirement, clone 
summary: Wenn Sie eine Datenbank klonen, können Sie Aufgaben wie das Testen eines Upgrades auf eine Datenbank durchführen, ohne die produktive Datenbank zu beeinträchtigen, eine Master-Installation auf mehrere Trainingssysteme zu duplizieren oder eine Master-Installation als Basisinstallation auf andere Server mit ähnlichen Anforderungen zu duplizieren. 
---
= Klonen der Datenbank-Backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine Datenbank klonen, können Sie Aufgaben wie das Testen eines Upgrades auf eine Datenbank durchführen, ohne die produktive Datenbank zu beeinträchtigen, eine Master-Installation auf mehrere Trainingssysteme zu duplizieren oder eine Master-Installation als Basisinstallation auf andere Server mit ähnlichen Anforderungen zu duplizieren.

Sie können die folgenden Aufgaben zum Klonen ausführen:

* Klonen einer Datenbank aus einem vorhandenen Backup
* Klonen einer Datenbank im aktuellen Status, mit der Sie das Backup und den Klon in einem Verfahren erstellen können.
* Klonen Sie eine Datenbank und verwenden Sie benutzerdefinierte Plug-in-Skripte, die vor oder nach dem Klonvorgang ausgeführt werden.
* Klonen einer Datenbank auf demselben Host, auf dem sich die Datenbank befindet.
* Klonen einer Datenbank unter Verwendung von Archivprotokolldateien aus dem externen Archivprotokoll.
* Klonen einer Datenbank auf einem alternativen Host
* Zeigen Sie eine Liste von Klonen an.
* Anzeigen von detaillierten Kloninformationen
* Klone löschen

