---
permalink: windows/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, user, allow, resource, repository, repositories, host, profile, credential, management 
summary: Sie können die Sicherheit in SnapManager durch Benutzerauthentifizierung verwalten. Die Benutzerauthentifizierungsmethode ermöglicht den Zugriff auf Ressourcen wie Repositorys, Hosts und Profile. 
---
= Sicherheits- und Anmeldeinformationsmanagement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Sicherheit in SnapManager durch Benutzerauthentifizierung verwalten. Die Benutzerauthentifizierungsmethode ermöglicht den Zugriff auf Ressourcen wie Repositorys, Hosts und Profile.

Wenn Sie einen Vorgang über die Befehlszeilenschnittstelle (CLI) oder die grafische Benutzeroberfläche (GUI) ausführen, ruft SnapManager die für Repositorys und Profile festgelegten Anmeldeinformationen ab. SnapManager speichert Anmeldeinformationen früherer Installationen.

Das Repository und die Profile können mit einem Passwort gesichert werden. Eine Anmeldeinformationen ist das für den Benutzer für ein Objekt konfigurierte Passwort, und das Passwort ist nicht für das Objekt selbst konfiguriert.

Sie können die Authentifizierung und Anmeldeinformationen verwalten, indem Sie die folgenden Aufgaben ausführen:

* Verwalten Sie die Benutzerauthentifizierung entweder durch Eingabeaufforderungen für Passwörter für Vorgänge oder mithilfe des `smsap credential set` Befehl.
+
Legen Sie Anmeldedaten für ein Repository, einen Host oder ein Profil fest.

* Zeigen Sie die Anmeldeinformationen an, die die Ressourcen regeln, auf die Sie Zugriff haben.
* Löschen Sie die Anmeldeinformationen eines Benutzers für alle Ressourcen (Hosts, Repositorys und Profile).
* Löschen Sie die Anmeldeinformationen eines Benutzers für einzelne Ressourcen (Hosts, Repositorys und Profile).



NOTE: Wenn sich die Repository-Datenbank auf einem Windows-Host befindet, müssen sowohl der lokale Benutzer als auch der Domänenbenutzer über dieselben Anmeldeinformationen verfügen.
