---
permalink: windows/reference-the-backint-register-sld-command.html 
sidebar: sidebar 
keywords: sap, br, tools, backint, register-sld, command, snapmanager, interface, landscape, system, directory, sld, vendor 
summary: 'Wenn Sie SAP BR*Tools verwenden möchten, können Sie den Befehl backint Register-sld mit SnapManager für SAP ausführen, um die BACKINT-Schnittstelle im Systemlandschaftsverzeichnis (SLD) zu registrieren. Die BACKINT Schnittstelle wird vom Storage-Anbieter bereitgestellt, damit das Storage-System mit den BR*Tools Befehlen kompatibel ist. SnapManager für SAP installiert seine BACKINT Interface-Datei bei C:\Program Files\NetApp\SnapManager für SAP\bin\.' 
---
= Der Befehl backint Register-sld
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie SAP BR*Tools verwenden möchten, können Sie den ausführen `backint register-sld` Befehl mit SnapManager für SAP zum Registrieren der BACKINT-Schnittstelle im SystemLandscape Directory (SLD). Die BACKINT Schnittstelle wird vom Storage-Anbieter bereitgestellt, damit das Storage-System mit den BR*Tools Befehlen kompatibel ist. SnapManager für SAP installiert seine BACKINT-Schnittstellendatei bei `C:\Program Files\NetApp\SnapManager for SAP\bin\`.



== Syntax

[listing]
----

backint register-sld
-host  host_name
-port  port_id
-username username
-password password
-template template_ID
----


== Parameter

* *`-host _host_name_`*
+
Gibt den Namen des Hosts an, auf dem die SAP SLD ausgeführt wird.

* *`-port _port_id_`*
+
Gibt die ID des Ports an, auf dem der SAP SLD HTTP-Anfragen akzeptiert. Die ID muss numerisch und kleiner als oder gleich neun Ziffern sein.

* *`-username _username_`*
+
Gibt einen gültigen und autorisierten SAP SLD-Benutzernamen an.

* *`-password _password_`*
+
Gibt ein gültiges und autorisiertes SAP SLD-Benutzerpasswort an. Dies ist optional. Wenn Sie das Passwort nicht mit festlegen `-password`, Sie werden aufgefordert, ein Passwort im folgenden Format einzugeben: `+username@http://host:port+`

+
Wenn Sie das korrekte Passwort nicht eingeben, schlägt der Befehl nach drei Versuchen fehl und wird beendet.

* *`-template _template_id_`*
+
Gibt den Namen der XML-Master-Vorlage an, die als Basis für Ihre benutzerdefinierte Datei verwendet werden kann.





== Beispielbefehl

Das folgende Beispiel zeigt, dass der Befehl erfolgreich abgeschlossen wurde:

[listing]
----
backint register-sld -host jack12 -port 50100
-username j2ee_admin -password user123 -template E:\template.xml
Operation Id [N96f4142a1442b31ee4636841babbc1d7] succeeded.
----