---
permalink: windows/reference-the-smosmsap-clone-update-command.html 
sidebar: sidebar 
keywords: command, update, information, clone, comment, smsap 
summary: Mit diesem Befehl werden Informationen zum Klon aktualisiert. Sie können den Kommentar aktualisieren. 
---
= Der Befehl smsap Clone Update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl werden Informationen zum Klon aktualisiert. Sie können den Kommentar aktualisieren.



== Syntax

[listing]
----

smsap clone update
-profile profile_name
[-label label | -id id]
-comment  commment_text
[-quiet | -verbose]
----


== Parameter

* *`-profile _profile_name_`*
+
Gibt den Namen des Profils an, das den zu aktualisierenden Klon enthält. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* *`-id _id_`*
+
Gibt die ID für den Klon an. Die ID wird von SnapManager beim Erstellen eines Klons generiert. Verwenden Sie die `smsap clone list` Befehl zum Anzeigen der ID für jeden Klon.

* *`-label _label_`*
+
Gibt die Bezeichnung für den Klon an.

* *`-comment`*
+
Zeigt den Kommentar an, der bei der Klonerstellung eingegeben wurde. Dies ist ein optionaler Parameter.

* *`-quiet`*
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *`-verbose`*
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl

Im folgenden Beispiel wird der Klonkommentar aktualisiert.

[listing]
----
smsap clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT  -comment See updated clone
----