---
permalink: windows/reference-the-smosmsapclone-show-command.html 
sidebar: sidebar 
keywords: run, clone, show, command, display, information, database, profile, smsap 
summary: Sie können den Befehl Clone show ausführen, um Informationen über die Datenbankklone für das angegebene Profil anzuzeigen. 
---
= Der Befehl smsap Clone show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ausführen `clone show` Befehl zum Anzeigen von Informationen über die Datenbankklone für das angegebene Profil.



== Syntax

[listing]
----

smsap clone show
-profile profile_name
[-id  guid | -label clone_name]
[-quiet | -verbose]
----


== Parameter

* *`-profile _profile_name_`*
+
Gibt die Liste der mit dem Profil verknüpften Klone an. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* *`-id _guid_`*
+
Zeigt Informationen über den Klon mit der angegebenen GUID an. Die GUID wird von SnapManager beim Erstellen eines Klons generiert. Sie können das verwenden `smsap clone show` Befehl zum Anzeigen der GUID für jeden Klon.

* *`-label _label_name_`*
+
Zeigt Informationen über den Klon mit der angegebenen Bezeichnung an.

* *`-quiet`*
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *`-verbose`*
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an.





== Beispiel

Im folgenden Beispiel werden Informationen über den Klon angezeigt:

[listing]
----
smsap clone show -profile SALES1 -label full_backup_sales_May -verbose
----
Die folgende Ausgabe zeigt Informationen zu einem Backup-Klon des primären Storage:

[listing]
----
Clone id: 8abc013111b916e30111b916ffb40001
Clone status: SUCCESS
Clone SID: hsdbc
Clone label: hsdbc
Clone comment: null
Clone start time: 2007-04-03 16:15:50
Clone end time: 2007-04-03 16:18:17
Clone host: Host1
Filesystem: E:\ssys1\data_clone\
File: E:\ssys1\data_clone\hsdb\sysaux01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs01.dbf
File: E:\ssys1\data_clone\hsdb\users01.dbf
File: E:\ssys1\data_clone\hsdb\system01.dbf
File: E:\ssys1\data_clone\hsdb\undotbs02.dbf
Backup id: 8abc013111a450480111a45066210001
Backup label: full_backup_sales_May
Backup SID: hsdb1
Backup comment:
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Backup host: server1
----