---
permalink: windows/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap 
summary: Mit diesem Befehl können Sie die Anmeldeinformationen für Benutzer festlegen, die auf sichere Ressourcen wie Hosts, Repositorys und Datenbankprofile zugreifen können. Das Hostpasswort ist das Passwort des Benutzers auf dem Host, auf dem SnapManager ausgeführt wird. Das Repository-Kennwort ist das Kennwort des Oracle-Benutzers, der das SnapManager-Repository-Schema enthält. Das Profilkennwort ist ein Passwort, das von der Person, die das Profil erstellt, gebildet wird. Wenn bei den Host- und Repository-Optionen die Option optional -password nicht enthalten ist, werden Sie aufgefordert, ein Kennwort des in den Befehlsargumenten angegebenen Typs einzugeben. 
---
= Der Befehl smsap Anmeldeinformationssatz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl können Sie die Anmeldeinformationen für Benutzer festlegen, die auf sichere Ressourcen wie Hosts, Repositorys und Datenbankprofile zugreifen können. Das Host-Passwort ist das Passwort des Benutzers auf dem Host, auf dem SnapManager ausgeführt wird. Das Repository-Kennwort ist das Kennwort des Oracle-Benutzers, der das SnapManager-Repository-Schema enthält. Das Profilkennwort ist ein Passwort, das von der Person, die das Profil erstellt, gebildet wird. Für die Host- und Repository-Optionen, falls optional `-password` Option ist nicht enthalten. Sie werden aufgefordert, ein Passwort des in den Befehlsargumenten angegebenen Typs einzugeben.



== Syntax

[listing]
----

smsap credential set
[-host
-name host_name
-username username]
[-password password]] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username] [-password repo_password]]
-port repo_port |
[-profile
-name profile_name]
[-password password]]
[-quiet | -verbose]
----


== Parameter

* *`-host _hostname_`*
+
Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem SnapManager ausgeführt wird.

+
Der `-host` Parameter enthält die folgenden Optionen:

+
** `-name host_name`: Gibt den Namen des Hosts an, für den Sie das Passwort festlegen möchten.
** `-username user_name`: Gibt den Benutzernamen auf dem Host an.
** `-password password`: Gibt das Passwort des Benutzers auf dem Host an.


* *`-repository -dbname`*
+
Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

+
Der `-repository` Parameter enthält die folgenden Optionen:

+
** `-dbnamerepo_service_name`: Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.
** `-host repo_host`: Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem die Repository-Datenbank ausgeführt wird.
** `-login-username repo_username`: Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank benötigt wird, in der das Repository gespeichert ist.
** `-password password`: Gibt das Kennwort an, das für den Zugriff auf die Datenbank benötigt wird, in der das Repository gespeichert ist.
** `-port repo_port`: Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.


* *`-profile -name _profile_name_`*
+
Gibt das Profil an, mit dem die Datenbank verknüpft ist.

+
Der `-profile` Parameter enthält die folgende Option:

+
** `-name profilename`: Gibt den Namen des Profils an, für das Sie das Passwort festlegen.
** `-password password`: Gibt das Passwort an, das für den Zugriff auf das Profil erforderlich ist.


* *`-quiet`*
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *`-verbose`*
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl zum Festlegen von Repository-Anmeldedaten

Im folgenden Beispiel werden Anmeldeinformationen für ein Repository festgelegt.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== Beispiel-Befehl zum Festlegen von Host-Anmeldedaten

Da eine Hostanmeldeinformationen eine tatsächliche Betriebssystemanmeldeinformationen darstellen, muss sie zusätzlich zum Passwort den Benutzernamen enthalten.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----