---
permalink: windows/task-unmounting-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, unmount, backup, available, external, tool, oracle, recovery, manager, rman, file, remove, access 
summary: 'SnapManager hängt automatisch das Backup ab, damit es nicht auf dem Host-Server verfügbar ist. Mit SnapManager können Sie auch die Bereitstellung aufheben, wenn Sie ein externes Tool wie beispielsweise Oracle Recovery Manager \(RMAN\) verwenden, um auf die Dateien im Backup zuzugreifen und den Status des Backups zum Entfernen des Zugriffs zu ändern.' 
---
= UnMounten von Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager hängt automatisch das Backup ab, damit es nicht auf dem Host-Server verfügbar ist. Mit SnapManager können Sie auch die Einbindung aufheben, wenn Sie ein externes Tool wie beispielsweise den Oracle Recovery Manager (RMAN) verwenden, um auf die Dateien im Backup zuzugreifen und den Zustand des Backups zu ändern, um den Zugriff zu entfernen.

Optional können Sie die Dump-Dateien nach einem erfolgreichen oder fehlgeschlagenen Unmount-Backup sammeln.

.Schritt
. Geben Sie den folgenden Befehl ein:
+
`smsap backup unmount -profile profile_name {labellabel [data | -archivelogs] | -idid} [-quiet | -verbose]`



*Verwandte Informationen*

xref:reference-the-smosmsapbackup-unmount-command.adoc[Der Befehl smsap Backup unmount]
