---
permalink: windows/task-update-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, backup, database, operate, system, authentication, information, host, oracle 
summary: 'Sie können die Profile aktualisieren, um das Profilkennwort, die Anzahl der zu behaltenden Backups, den Zugriff auf die Datenbank, die Betriebssystemauthentifizierung (OS) auf die Datenbankauthentifizierung und umgekehrt sowie Informationen zum Host zu ändern. Wenn sich die Kennwortinformationen der Oracle-Datenbank ändern, müssen Sie diese Informationen auch im Profil ändern.' 
---
= Profile aktualisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Profile aktualisieren, um das Profilkennwort, die Anzahl der zu behaltenden Backups, den Zugriff auf die Datenbank, die Betriebssystemauthentifizierung (OS) auf die Datenbankauthentifizierung und umgekehrt sowie Informationen zum Host zu ändern. Wenn sich die Kennwortinformationen der Oracle-Datenbank ändern, müssen Sie diese Informationen auch im Profil ändern.



== Über diese Aufgabe

Mit SnapManager (3.2 oder höher) können Sie das Profil aktualisieren, um Archiv-Log-Backups von den Datensicherungen der Datendatei mit dem zu trennen `-separate-archivelog-backups` Option. Sie können eine separate Aufbewahrungsdauer für das Backup des Archivprotokolls festlegen. Mit SnapManager können Sie das Archivprotokoll-Backup zusammen mit dem Online-Datenbank-Backup einbeziehen. Außerdem können Sie zum Klonen eine Online-Datendatei-Backup- und ein Archivprotokoll-Backup erstellen. Wenn Sie eine Sicherung von Online-Datendateien erstellen, werden die Archivprotokolle sofort zusammen mit den Datendateien erstellt.

.Schritt
. Geben Sie den folgenden Befehl ein:
+
`*smsap profile update -profile _profile_ [-new-profile _new_profile_name_] [-profile-password _profile_password_][-database _-dbnamedb_dbname_ -host _db_host_ [-sid _db_sid_] [-login -usernamedb_username-password _db_password-port_ _db_port_]] [{-rman{-controlfile | {-login  -username _rman_username_ -password  rman_password-tnsname  _rman_tnsname_}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern] [-summary-notification] [-notification [-success-email _email_address1_, _email_address2_ -subjects _ubject_pattern_] [-failure-email _email_address1_, _email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups-hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_ [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Weitere Optionen für diesen Befehl:

+
[`-force`] [`-noprompt`]

+
[`quiet` . `verbose`]

+
|===
| Ihr Ziel ist | Dann... 


 a| 
*Ändern Sie die Backup Retention Policy für Backups der Datenbank im Profil*
 a| 
Geben Sie entweder den Aufbewahrungszeitraum oder die Aufbewahrungsdauer für eine Aufbewahrungsklasse oder beides an, um die Aufbewahrungsrichtlinie zu ändern. Die Dauer ist in Einheiten der Klasse (z. B. Stunden für Stunde, Tage für Tag).

** `-hourly` Ist die Stunde Aufbewahrungsklasse, wofür [`-countn`] [`-durationm`]] sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.
** `-daily` Ist die tägliche Aufbewahrungsklasse, für die [`-countn`] [`-durationm`]] sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.
** `-weekly` Ist die wöchentliche Aufbewahrungsklasse, für die [`-countn`] [`-durationm`]] sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.
** -Monatlich ist die monatliche Aufbewahrungsklasse, dafür [`-countn`] [`-durationm`]] sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.




 a| 
*E-Mail-Benachrichtigungen für den Abschlussstatus der Datenbankvorgänge* aktivieren
 a| 
Geben Sie die folgenden Optionen und Variablen an:

** `-summary-notification` Ermöglicht die Konfiguration einer E-Mail-Benachrichtigung für mehrere Profile unter einer Repository-Datenbank.
** `-notification` Hiermit erhalten Sie eine E-Mail-Benachrichtigung über den Abschlussstatus des Datenbankvorgangs für ein Profil.
** `-success-emailemail_address2` Hiermit erhalten Sie eine E-Mail-Benachrichtigung, nachdem Sie einen erfolgreichen Datenbankvorgang abgeschlossen haben, der mit einem neuen oder einem vorhandenen Profil durchgeführt wird.
** `-failure-emailemail_address2` Hiermit erhalten Sie eine E-Mail-Benachrichtigung über einen fehlgeschlagenen Datenbankvorgang, der mit einem neuen oder einem vorhandenen Profil durchgeführt wird.
** `-subjectsubject_text` Gibt den Subjekttext für die E-Mail-Benachrichtigung an, während ein neues Profil oder ein vorhandenes Profil erstellt wird. Wenn die Benachrichtigungseinstellungen nicht für das Repository konfiguriert sind und Sie versuchen, Profile- oder Übersichtsbenachrichtigungen mithilfe der Befehlszeilenschnittstelle (CLI) zu konfigurieren, wird die folgende Meldung im Konsolenprotokoll protokolliert: `SMSAP-14577: Notification Settings not configured`.
+
Wenn Sie die Benachrichtigungseinstellungen konfiguriert haben und versuchen, eine zusammenfassende Benachrichtigung mithilfe der CLI zu konfigurieren, ohne dass eine zusammenfassende Benachrichtigung für das Repository aktiviert wird, wird die folgende Meldung im Konsole-Protokoll protokolliert: `SMSAP-14575: Summary notification configuration not available for this repository`





 a| 
*Aktualisieren Sie das Profil, um eine Sicherung der Archiv-Log-Dateien separat zu erstellen*
 a| 
Geben Sie die folgenden Optionen und Variablen an:

** `-separate-archivelog-backups` Ermöglicht die Erstellung einer Sicherungskopie der Archivprotokolldateien getrennt von den Datenbankdateien.
+
Nachdem Sie diese Option angegeben haben, können Sie entweder ein Datendatei-only Backup oder ein Backup nur mit Archivdateien erstellen. Sie können keine vollständige Sicherung erstellen. Außerdem können Sie die Profileinstellungen nicht durch Trennen der Sicherung zurücksetzen. SnapManager behält die Backups auf Basis der Aufbewahrungsrichtlinie für die Backups bei, die vor der Erstellung eines rein archivorientierten Backups erstellt wurden.

** `-retain-archivelog-backups` Legt die Aufbewahrungsdauer für Backups im Archivprotokoll fest.
+

NOTE: Wenn Sie das Profil zum ersten Mal aktualisieren, können Sie die Archiv-Log-Backups von der Datensicherung mit dem trennen `-separate-archivelog-backups` Option; Sie müssen die Aufbewahrungsdauer für die Backups des Archivprotokolls mithilfe des angeben `-retain-archivelog-backups` Option. Die Einstellung der Aufbewahrungsdauer ist optional, wenn Sie das Profil später aktualisieren.

** `-include-with-online-backups` Gibt an, dass das Backup des Archivprotokolls zusammen mit dem Datenbank-Backup enthalten ist.
** `-no-include-with-online-backups` Gibt an, dass die Sicherung der Archivprotokolldatei nicht zusammen mit dem Datenbank-Backup enthalten ist.




 a| 
*Ändern Sie den Hostnamen der Zieldatenbank*
 a| 
Angeben `-hostnew_db_host` So ändern Sie den Hostnamen des Profils.



 a| 
*Sammeln Sie die Dump-Dateien nach dem Profil-Update-Vorgang*
 a| 
Geben Sie die an `-dump` Option.

|===
. Geben Sie den folgenden Befehl ein, um das aktualisierte Profil anzuzeigen: `smsap profile show`

