---
permalink: windows/task-customizing-the-email-subject-for-an-existing-profile.html 
sidebar: sidebar 
keywords: snapmanager, enable, customize, email, subject, pattern, exist, profile, applicable, update, customizing 
summary: SnapManager ermöglicht Ihnen, das Muster des E-Mail-Betreff für ein bestehendes Profil anzupassen, indem Sie dieses Profil aktualisieren. Dieses benutzerdefinierte Muster für Studienteilnehmer gilt nur für das aktualisierte Profil. 
---
= Anpassen des E-Mail-Betreff für ein vorhandenes Profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager ermöglicht Ihnen, das Muster des E-Mail-Betreff für ein bestehendes Profil anzupassen, indem Sie dieses Profil aktualisieren. Dieses benutzerdefinierte Muster für Studienteilnehmer gilt nur für das aktualisierte Profil.

. Geben Sie den folgenden Befehl ein:
+
`smsap profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password db_password-port db_port]] [{-rman{-controlfile | {-login  -usernamerman_username-password  rman_password-tnsname  rman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][[-protect [-protection-policypolicy_name]]| [[-noprotect]] [-notification [-success-emailemail_address1,email_address2-subjectsubject_pattern] [-failure-emailemail_address1,email_address2-subjectsubject_pattern]]`


