---
permalink: windows/task-changing-the-retention-policy-default-behavior.html 
sidebar: sidebar 
keywords: backup, expire, retention, policy, snapmanager, delete, setting 
summary: Wenn ein Backup basierend auf der Aufbewahrungsrichtlinie abläuft, bestimmt SnapManager basierend auf den Aufbewahrungseinstellungen, ob das Backup gelöscht werden soll. Das Löschen von Backups ist das Standardverhalten. Sie können dieses Standardverhalten ändern und stattdessen die ungeschützten Backups freigeben. 
---
= Ändern des Standardverhaltens der Aufbewahrungsrichtlinie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Backup basierend auf der Aufbewahrungsrichtlinie abläuft, bestimmt SnapManager basierend auf den Aufbewahrungseinstellungen, ob das Backup gelöscht werden soll. Das Löschen von Backups ist das Standardverhalten. Sie können dieses Standardverhalten ändern und stattdessen die ungeschützten Backups freigeben.

Standardmäßig löscht Snap Manager das Backup nach Ablauf des Backup.

. Zugriff auf den folgenden Standardspeicherort:
+
Standard smsap Installationsort\Properties\smsap.config

. Bearbeiten Sie die Datei smsap.config.
. Legen Sie in der Datei smsap.config die Eigenschaft contee.alwayFreeExpiredBackups auf true fest.
+
Beispiel: `retain.alwaysFreeExpiredBackups = true`



*Verwandte Informationen*

xref:reference-the-smosmsapbackup-update-command.adoc[Der Befehl smsap Backup Update]
