---
permalink: windows/task-verifying-database-backups.html 
sidebar: sidebar 
keywords: backup, verify, command, block, database, corrupt, operation, invoke, oracle, utility, data, file, backup 
summary: Sie können mit dem Befehl Backup Verify überprüfen, ob die Blöcke im Datenbank-Backup nicht beschädigt sind. Der Verify-Vorgang ruft das Dienstprogramm Oracle Database Verify für jede Datendatei im Backup auf. 
---
= Datenbank-Backups werden überprüft
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mit dem Befehl Backup Verify überprüfen, ob die Blöcke im Datenbank-Backup nicht beschädigt sind. Der Verify-Vorgang ruft das Dienstprogramm Oracle Database Verify für jede Datendatei im Backup auf.

Mit SnapManager können Sie den Verifizierungsvorgang jederzeit für Sie und die Benutzer in Ihrem System durchführen. Sie können die Verifizierung sofort nach dem Erstellen des Backups durchführen. Sie müssen das Profil angeben, das das Backup enthält, und entweder die Bezeichnung oder die ID des erstellten Backups.


NOTE: Die Backup-Überprüfung schlägt in einer Windows-Umgebung fehl, wenn Sie SnapManager 3.0 und Oracle Database 11.1.0.7 verwenden. Sie müssen Oracle Database 11.2.0.1 oder höher verwenden.


NOTE: Sie können -dump angeben, um die Dump-Dateien nach der Backup-Überprüfung zu sammeln.

. Geben Sie den folgenden Befehl ein:
+
`smsap backup verify -profile profile_name [-label label | -id id] [-force] [ -dump] [-quiet | -verbose]`



*Verwandte Informationen*

xref:reference-the-smosmsapbackup-verify-command.adoc[Der Befehl smsap Backup verify]
