---
permalink: windows/task-cloning-a-database-to-an-alternate-host.html 
sidebar: sidebar 
keywords: clone, command, database, alternate, host, cloning 
summary: Sie können mit dem Befehl Clone create ein Datenbank-Backup auf einem alternativen Host klonen. 
---
= Klonen einer Datenbank auf einem alternativen Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mit dem Befehl Clone create ein Datenbank-Backup auf einem alternativen Host klonen.

* Erstellen Sie ein Profil oder haben Sie ein vorhandenes Profil.
* Erstellen Sie ein vollständiges Backup oder ein bereits vorhandenes Datenbank-Backup.
* Erstellen Sie eine Klonspezifikation oder weisen Sie eine vorhandene Klonspezifikation auf.


.Schritt
. Geben Sie den folgenden Befehl ein, um eine Datenbank auf einem alternativen Host zu klonen:
+
`smsap clone create -backup-labelbackup_label_name-newsidnew_sid-hosttarget_host-labelclone_label-comment comment_text-profileprofile_name-clonespecfull_path_to_clonespecfile`

+
Oracle lässt Sie nicht zwei Datenbanken mit derselben SID gleichzeitig auf dem gleichen Host laufen. Aus diesem Grund müssen Sie für jeden Klon eine neue SID angeben. Sie können jedoch eine Datenbank auf einem anderen Host mit derselben SID haben.



*Verwandte Informationen*

xref:task-creating-profiles.adoc[Profile werden erstellt]

xref:task-cloning-databases-from-backups.adoc[Klonen von Datenbanken aus Backups]

xref:task-creating-clone-specifications.adoc[Erstellen von Klonspezifikationen]

xref:reference-the-smosmsapclone-create-command.adoc[Der Befehl smsap Clone create]
