---
permalink: windows/task-configure-history-for-backup-operation.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, maintain, history, operation, cli, gui, history, operation, report, configure 
summary: Mit SnapManager für SAP können Sie den Verlauf des SnapManager-Vorgangs über die Befehlszeilenschnittstelle oder Benutzeroberfläche von SnapManager aufrechterhalten. Sie können den Verlauf der SnapManager-Operation als Bericht anzeigen. 
---
= Konfigurieren Sie den Verlauf für den SnapManager-Betrieb
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapManager für SAP können Sie den Verlauf des SnapManager-Vorgangs über die Befehlszeilenschnittstelle oder Benutzeroberfläche von SnapManager aufrechterhalten. Sie können den Verlauf der SnapManager-Operation als Bericht anzeigen.

.Schritt
. Geben Sie den folgenden Befehl ein, um den Verlauf des SnapManager-Vorgangs zu konfigurieren:
+
`*smsap history set -profile {-name, _profile_name_ [_profile_name1_, _profile_name2_] | _-all_ -repository -login [-password _repo_password_] -username _repo_username_ -dbname _repo_dbname_ -host _repo_host_ -port _repo_port_} -operation {-operations _operation_name_ [_operation_name1_, _operation_name2_] | -all} -retain {-count _retain_count_ | -daily _retain_daily_ | -weekly _retain_weekly_ | -monthly _retain_monthly_} [-quiet | -verbose]*`



[listing]
----

        smsap
history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6 -verbose
----
[listing]
----

        smsap
history set -profile -name PROFILE1 -operation -all -retain -weekly 3 -verbose
----