---
permalink: windows/task-creating-clone-specifications.html 
sidebar: sidebar 
keywords: snapmanager, sap, clone, specification, xml, file, mapping, option, parameter, clone, operation, information, creating, create 
summary: SnapManager für SAP verwendet eine XML-Datei für die Klonspezifikation, die die Zuordnungen, Optionen und Parameter für die Verwendung im Klonvorgang umfasst. SnapManager verwendet diese Informationen, um zu bestimmen, wo die von ihm klonen und wie mit Diagnosedaten, Kontrolldateien, Parametern usw. umzugehen ist. 
---
= Erstellen von Klonspezifikationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager für SAP verwendet eine XML-Datei für die Klonspezifikation, die die Zuordnungen, Optionen und Parameter für die Verwendung im Klonvorgang umfasst. SnapManager verwendet diese Informationen, um zu bestimmen, wo die von ihm klonen und wie mit Diagnosedaten, Kontrolldateien, Parametern usw. umzugehen ist.

Sie können die Klon-Spezifikationsdatei über die grafische Benutzeroberfläche von SnapManager (GUI), die Befehlszeilenschnittstelle (CLI) oder einen Texteditor erstellen.

Wenn Sie die Clone Specification-Datei mithilfe eines Texteditors erstellen, müssen Sie sie als XML-Datei speichern. Sie können diese XML-Datei für andere Klonvorgänge verwenden.

Sie können auch eine Vorlage für Klonspezifikationen erstellen und diese dann anpassen. Sie können den Befehl smsap Clone template oder in der GUI verwenden, den Clone Wizard verwenden.

SnapManager für SAP fügt einer beliebigen Klon-Spezifikations-Vorlage, die sie erstellt, einen Versionsstring hinzu. SnapManager für SAP geht von der aktuellen Version jeder Klon-Spezifikations-Datei aus, die keine Versionszeichenfolge aufweist.

Wenn Sie Remote-Klone durchführen möchten, ändern Sie in der Klonspezifikationsdatei nicht die Standardorte der Datendateien, Wiederherstellungsprotokolle und Kontrolldateien. Wenn Sie den Standardspeicherort ändern, erstellt SnapManager nicht den Klon oder erstellt den Klon für einer Datenbank, die keine Snapshot-Funktion unterstützt. Daher schlägt die automatische Profilerstellung fehl.


NOTE: Obwohl Mount-Punkt- und ASM-Datenträgergruppen-Informationen über die GUI editierbar sind, können Sie nur den Dateinamen und nicht die Dateiorte ändern.

Sie können eine Aufgabe mehrfach ausführen, entweder mit den gleichen oder mit unterschiedlichen Parameter- und Wertkombinationen.

SAP verwendet bestimmte Oracle Einstellungen für die Datenbankkonfiguration. Sie finden diese Einstellungen in init<SID>.ora bei €3b ORACLE_HOME\Datenbank. Sie sollten diese in Ihre Klonspezifikation aufnehmen.

. Öffnen Sie eine Textdatei und geben Sie Text ein, wie im folgenden Beispiel gezeigt:
+
[listing]
----
<clone-specification xmlns="http://www.example.com>
     <storage-specification/>
     <database-specification/>
 </clone-specification>
----
. Geben Sie in der Komponente Speicherspezifikation die Bereitstellungspunkte für die Datendateien ein.
+
In der Storage-Spezifikation werden die Speicherorte für den für den Klon erstellten neuen Storage aufgeführt, wie z. B. Mount-Punkte für Datendateien und Rohgeräte. Diese Elemente müssen vom Quell- dem Ziel zugeordnet werden.

+
Das folgende Beispiel zeigt einen einzelnen NFS-Bereitstellungspunkt auf einem NFS-Attached Storage:

+
[listing]
----
<mountpoint>
      <source>\oracle\<SOURCE SID>_sapdata</source>
      <destination>\oracle\<TARGET SID>_sapdata</destination>
</mountpoint>
----
. Geben Sie in der Komponente Datenbankspezifikation die Informationen der Steuerdatei als eine Liste der Steuerdateien an, die Sie für den Klon erstellen möchten.
+
Die Datenbankspezifikation gibt die Datenbankoptionen für den Klon an, z. B. Kontrolldateien, Wiederherstellungsprotokolle, Archivprotokolle und Oracle Parameter.

+
Im folgenden Beispiel wird die Syntax der Kontrolldatei angezeigt, die Sie in der Klonspezifikation verwenden:

+
[listing]
----
<controlfiles>
     <file>\oracle\<TARGET SID>\origlogA\cntrl\cntrl<TARGET SID>.dbf</file>
     <file>\oracle\<TARGET SID>\origlogB\cntrl\cntrl<TARGET SID>.dbf</file>
     <file>\oracle\<TARGET SID>\sapdata1\cntrl\cntrl<TARGET SID>.dbf</file>
</controlfiles>
----
. Geben Sie die Struktur des Wiederherstellungsprotokolls für den Klon an.
+
Im folgenden Beispiel wird die Struktur des Wiederherstellungsprotokollverzeichnisses für das Klonen angezeigt:

+
[listing]
----
<redologs>
     <redogroup>
        <file>E:\oracle\<TARGET SID>\origlogA\log_g11m1.dbf</file>
        <file>E:\oracle\<TARGET SID>\mirrlogA\log_g11m2.dbf</file>
        <number>1</number>
        <size unit="M">100</size>
     </redogroup>
     <redogroup>
        <file>E:\oracle\<TARGET SID>\origlogB\log_g12m1.dbf</file>
        <file>E:\oracle\<TARGET SID>\mirrlogB\log_g12m2.dbf</file>
        <number>2</number>
        <size unit="M">100</size>
     </redogroup>
     <redogroup>
        <file>E:\oracle\<TARGET SID>\origlogA\log_g13m1.dbf</file>
        <file>E:\oracle\<TARGET SID>\mirrlogA\log_g13m2.dbf</file>
        <number>3</number>
        <size unit="M">100</size>
     </redogroup>
     <redogroup>
        <file>E:\oracle\<TARGET SID>\origlogB\log_g14m1.dbf</file>
        <file>E:\oracle\<TARGET SID>\mirrlogB\log_g14m2.dbf</file>
        <number>4</number>
        <size unit="M">100</size>
     </redogroup>
</redologs>
----
. Geben Sie die Oracle-Parameter an, die in der geklonten Datenbank auf unterschiedliche Werte festgelegt werden sollen. Wenn Sie Oracle 10 verwenden, müssen Sie die folgenden Parameter angeben:
+
** Hintergrundauszug
** Core Dump
** User Dump
** (Optional) Archivprotokolle
+

NOTE: Wenn die Parameterwerte nicht richtig festgelegt sind, wird der Klonvorgang angehalten, und Sie erhalten eine Fehlermeldung.



+
Wenn Sie nicht den Speicherort der Archivprotokolle angeben, erstellt SnapManager den Klon im Noarchivelog Modus. SnapManager kopiert diese Parameterinformationen in die init.ora-Datei des Klons.

+
+ im folgenden Beispiel wird die Parametersyntax angezeigt, die Sie in der Klonspezifikation verwenden:

+
+

+
[listing]
----
<parameters>
     <parameter>
          <name>log_archive_dest</name>
          <value>LOCATION=>E:\oracle\<TARGET SID>\oraarch</value>
     </parameter>
     <parameter>
          <name>background_dump_dest</name>
          <value>E:\oracle\<TARGET SID>\saptrace\background</value>
     </parameter>
     <parameter>
          <name>core_dump_dest</name>
          <value>E:\oracle\<TARGET SID>\saptrace\background</value>
     </parameter>
     <parameter>
     <name>user_dump_dest</name>
     <value>E:\oracle\<TARGET SID>\saptrace\usertrace</value>
     </parameter>
</parameters>
----
+
+ Sie können einen Standardwert verwenden, indem Sie ein Standardelement innerhalb des Parameterelements verwenden. Im folgenden Beispiel übernimmt der Parameter os_Authentication_PREFIX den Standardwert, da das Standardelement angegeben wird:

+
+

+
[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <default></default>
     </parameter>
</parameters>
----
+
+ Sie können einen leeren String als Wert für einen Parameter mithilfe eines leeren Elements angeben. Im folgenden Beispiel wird das os_Authentication_PREFIX auf einen leeren String gesetzt:

+
+

+
[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <value></value>
     </parameter>
</parameters>
----
+
+ HINWEIS: Sie können den Wert aus der init.ora-Datei der Quelldatenbank für den Parameter verwenden, indem Sie kein Element angeben.

+
+ Wenn ein Parameter mehrere Werte hat, können Sie die durch Kommas getrennten Parameterwerte angeben. Wenn Sie beispielsweise die Datendateien von einem Ort in einen anderen verschieben möchten, können Sie den Parameter db_file_Name_convert verwenden und die durch Kommas getrennten Datendateipfade angeben, wie im folgenden Beispiel zu sehen ist:

+
+ Wenn Sie die Protokolldateien von einem Ort in einen anderen verschieben möchten, können Sie den Parameter log_file_Name_convert verwenden und die durch Kommas getrennten Protokolldateipfade angeben, wie im folgenden Beispiel zu sehen ist:

. Optional: Geben Sie beliebige SQL-Anweisungen an, die für den Klon ausgeführt werden sollen, wenn er online ist.
+
Sie können die SQL-Anweisungen verwenden, um Aufgaben auszuführen, wie z. B. das Neuerstellen der temporären Dateien in der geklonten Datenbank.

+

NOTE: Sie müssen sicherstellen, dass am Ende der SQL-Anweisung kein Semikolon enthalten ist.

+
Im Folgenden finden Sie eine Beispiel-SQL-Anweisung, die Sie im Rahmen des Klonvorgangs ausführen:

+
[listing]
----
<sql-statements>
   <sql-statement>
     ALTER TABLESPACE TEMP ADD
     TEMPFILE 'E:\path\clonename\temp_user01.dbf'
     SIZE 41943040 REUSE AUTOEXTEND ON NEXT 655360
     MAXSIZE 32767M
   </sql-statement>
</sql-statements>
----




== Beispiel für Klonspezifikation

Im folgenden Beispiel wird die Klonspezifikationsstruktur für eine Windows-Umgebung angezeigt, einschließlich der Komponenten für die Storage- und Datenbankspezifikation:

[listing]
----
<clone-specification xmlns="http://www.example.com>

<storage-specification>
    <storage-mapping>
        <mountpoint>
            <source>D:\oracle\<SOURCE SID>_sapdata</source>
            <destination>D:\oracle\<TARGET SID>_sapdata</destination>
        </mountpoint>
    </storage-mapping>
</storage-specification>

<database-specification>
    <controlfiles>
        <file>D:\oracle\<TARGET SID>\origlogA\cntrl\cntrl<TARGET SID>.dbf</file>
        <file>D:\oracle\<TARGET SID>\origlogB\cntrl\cntrl<TARGET SID>.dbf</file>
        <file>D:\oracle\<TARGET SID>\sapdata1\cntrl\cntrl<TARGET SID>.dbf</file>
     </controlfiles>

     <redologs>
        <redogroup>
            <file>D:\oracle\<TARGET SID>\origlogA\log_g11m1.dbf</file>
            <file>D:\oracle\<TARGET SID>\mirrlogA\log_g11m2.dbf</file>
            <number>1</number>
            <size unit="M">100</size>
        </redogroup>
        <redogroup>
            <file>D:\oracle\<TARGET SID>\origlogB\log_g12m1.dbf</file>
            <file>D:\oracle\<TARGET SID>\mirrlogB\log_g12m2.dbf</file>
            <number>2</number>
            <size unit="M">100</size>
        </redogroup>
        <redogroup>
            <file>D:\oracle\<TARGET SID>\origlogA\log_g13m1.dbf</file>
            <file>D:\oracle\<TARGET SID>\mirrlogA\log_g13m2.dbf</file>
            <number>3</number>
            <size unit="M">100</size>
        </redogroup>
        <redogroup>
            <file>D:\oracle\<TARGET SID>\origlogB\log_g14m1.dbf</file>
            <file>D:\oracle\<TARGET SID>\mirrlogB\log_g14m2.dbf</file>
            <number>4</number>
            <size unit="M">100</size>
       </redogroup>
    </redologs>

    <parameters>
        <parameter>
            <name>log_archive_dest</name>
            <value>LOCATION=>D:\oracle\<TARGET SID>\oraarch</value>
        </parameter>
        <parameter>
            <name>background_dump_dest</name>
            <value>D:\oracle\<TARGET SID>\saptrace\background</value>
        </parameter>
        <parameter>
            <name>core_dump_dest</name>
            <value>D:\oracle\<TARGET SID>\saptrace\background</value>
        </parameter>
        <parameter>
            <name>user_dump_dest</name>
            <value>D:\oracle\<TARGET SID>\saptrace\usertrace</value>
        </parameter>
    </parameters>
  </database-specification>
</clone-specification>
----
*Verwandte Informationen*

xref:task-cloning-databases-and-using-custom-plugin-scripts.adoc[Klonen von Datenbanken und mit benutzerdefinierten Plug-in-Skripten]

xref:task-cloning-databases-from-backups.adoc[Klonen von Datenbanken aus Backups]

xref:task-cloning-databases-in-the-current-state.adoc[Das Klonen von Datenbanken im aktuellen Status]

xref:concept-considerations-for-cloning-a-database-to-an-alternate-host.adoc[Überlegungen beim Klonen einer Datenbank auf einem alternativen Host]
