---
permalink: windows/task-viewing-detailed-clone-information.html 
sidebar: sidebar 
keywords: view, detail, information, specific, clone, show, command 
summary: Mit dem Befehl Clone show können Sie ausführliche Informationen über einen bestimmten Klon anzeigen. 
---
= Anzeigen detaillierter Kloninformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Befehl Clone show können Sie ausführliche Informationen über einen bestimmten Klon anzeigen.

Mit dem Befehl Clone show werden die folgenden Informationen angezeigt:

* Systemidentifikation und Klon-ID klonen
* Status des Klonvorgangs
* Start- und Enddatum bzw. -Uhrzeit des Klons
* Klonbezeichnung
* Klonkommentar
* Backup-Label und -ID
* Quelldatenbank
* Start- und Endzeit des Backups
* Datenbankname, Tabellen und Datendateien
* Host-Name und Dateisysteme mit Datendateien
* Storage-System-Volumes und Snapshot-Kopien, die den Klon sichern


.Schritt
. Geben Sie den folgenden Befehl ein:
+
`smsap clone show -profile profile_name [-label label | -idguid]`



*Verwandte Informationen*

xref:reference-the-smosmsapclone-show-command.adoc[Der Befehl smsap Clone show]
