---
permalink: windows/task-enable-autosupport-in-snapmanager.html 
sidebar: sidebar 
keywords: enable, autosupport, storage, system, receive, message, snapmanager, server, successful, backup, operation, enable 
summary: Sie müssen AutoSupport aktivieren, damit Storage-Systeme bei jedem erfolgreichen Backup-Vorgang Meldungen vom SnapManager-Server empfangen. 
---
= Aktivieren Sie AutoSupport in SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen AutoSupport aktivieren, damit Storage-Systeme bei jedem erfolgreichen Backup-Vorgang Meldungen vom SnapManager-Server empfangen.



== Über diese Aufgabe

AutoSupport kann auf zwei Arten aktiviert werden:

* Standardmäßig enthält die neue Installation von SnapManager nicht `auto_support.on` Parameter in `smsap.config` Konfigurationsdatei Dies impliziert, dass AutoSupport aktiviert ist.
* Sie können die manuell konfigurieren `auto_support.on` Parameter.


.Schritte
. Beenden Sie den SnapManager-Server.
. Im `smsap.config` Konfigurationsdatei, legen Sie den Wert des fest `auto_support.on` Parameter auf *TRUE*.
+
*Beispiel*

+
auto_Support.on=TRUE

. Starten Sie den SnapManager-Server neu.

