---
permalink: windows/task-create-profiles.html 
sidebar: sidebar 
keywords: create, profile, assign, oracle, database, policy, set, retention, count, class 
summary: Beim Erstellen von Profilen können Sie dem Profil ein bestimmtes Oracle-Datenbankbenutzerkonto zuweisen. Sie können die Aufbewahrungsrichtlinie für das Profil festlegen und die Anzahl und Dauer der Aufbewahrung für jede Aufbewahrungsklasse festlegen. 
---
= Erstellen von Profilen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Erstellen von Profilen können Sie dem Profil ein bestimmtes Oracle-Datenbankbenutzerkonto zuweisen. Sie können die Aufbewahrungsrichtlinie für das Profil festlegen und die Anzahl und Dauer der Aufbewahrung für jede Aufbewahrungsklasse festlegen.



== Über diese Aufgabe

Wenn Sie die Werte des nicht angeben `-login`, `-password`, und `-port` Parameter der Datenbank verwendet der Authentifizierungsmodus des Betriebssystems die Standardanmeldeinformationen.

Während der Erstellung eines Profils führt SnapManager eine Überprüfung der Berechtigung zur Wiederherstellung durch, um den Wiederherstellungsmechanismus zu bestimmen, mit dem die Datenbank wiederhergestellt werden kann.

Mit SnapManager (3.2 oder höher) können Sie Archivprotokolldateien von den Datendateien trennen, während Sie ein neues Profil erstellen oder ein vorhandenes Profil aktualisieren. Nachdem Sie die Sicherung mit dem Profil getrennt haben, können Sie entweder nur die Datendateien-only-Backup oder Archiv-Log-only-Backup der Datenbank erstellen. Sie können das neue Profil oder das aktualisierte Profil verwenden, um das Backup zu erstellen, das sowohl die Datendateien als auch die Archivprotokolldateien enthält. Sie können das Profil jedoch nicht zum Erstellen der vollständigen Sicherung oder zum Zurücksetzen der Einstellungen verwenden.

*Profile zur Erstellung vollständiger und partieller Backups*

Sie können Profile erstellen, um das vollständige Datenbank-Backup mit den Datendateien, Kontrolldateien, Archivprotokolldateien und partiellen Datenbank-Backups zu erstellen, die bestimmte Datendateien oder Tablespaces enthalten, alle Kontrolldateien und alle Archivprotokolldateien. SnapManager erlaubt Ihnen nicht, mithilfe der Profile, die für vollständige und teilweise Backups erstellt wurden, separate Archiv-Log-Backups zu erstellen.

*Profile zur Erstellung von nur-Datendateien-Backups und nur archivalogs-Backups*

Wenn Sie ein neues Profil erstellen, können Sie Folgendes einschließen `-separate-archivelog-backups` So trennen Sie das Backup des Archivprotokolls von der Datensicherung der Datendatei. Sie können das vorhandene Profil auch aktualisieren, um die Sicherung des Archivprotokolls von der Datensicherung der Datendatei zu trennen.

Mithilfe der neuen Profiloptionen können Sie die Backups des Archivprotokolls trennen und folgende SnapManager-Vorgänge durchführen:

* Erstellen Sie eine Backup-Datei für Archivprotokolle
* Löschen Sie eine Sicherung des Archivprotokolls
* Mounten Sie ein Backup für das Archivprotokoll
* Kostenlose Backup eines Archivprotokolls


Beim Erstellen des Profils zur Trennung von Archiv-Log-Backups von der Datendatei-Sicherung, wenn die Archivprotokolldateien nicht in der Datenbank vorhanden sind, für die das Profil erstellt wird, wird eine Warnmeldung angezeigt.


WARNING: `Archived log file does not exist in the active file system. The archived log file versions earlier than the <archive log thread version> log file will not be included in the backup`

Selbst wenn Sie Backups für diese Datenbank erstellen, sind die Archiv-Log-Dateien in den Datenbank-Backups nicht verfügbar.


NOTE: Wenn beim Erstellen eines Profils ein Fehler auftritt, verwenden Sie den `smsap system dump` Befehl. Verwenden Sie nach dem Erstellen eines Profils den, wenn ein Fehler auftritt `smsap operation dump` Und `smsap profile dump` Befehle.

.Schritt
. Um ein Profil mit einem Benutzernamen, Kennwort und Port (Oracle-Authentifizierung) zu erstellen, geben Sie den folgenden Befehl ein:
+
`*smsap profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_dbname-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]][-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Weitere Optionen für diesen Befehl:

+
[`-force`] [`-noprompt`]

+
[`quiet` . `verbose`]

+
Je nach Zugriffsart auf die Datenbank können Sie auch weitere Optionen bei der Erstellung von Profilen berücksichtigen.

+
|===
| Wenn... | Dann... 


 a| 
*Sie möchten die Datenbankauthentifizierung verwenden, um ein Profil zu erstellen*
 a| 
Geben Sie die Anmeldedaten für die Datenbank an.



 a| 
*Sie wollen eine Backup Retention Policy für Backups* angeben
 a| 
Geben Sie entweder den Aufbewahrungszähler oder die Dauer für eine Aufbewahrungsklasse oder beides an. Die Dauer ist in Einheiten der Klasse (z. B. Stunden für Stunde, Tage für Tag).

** `-hourly` Ist die Stunde Aufbewahrungsklasse, wofür [`-count n`] [`-duration m`] Sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.
** `-daily` Ist die tägliche Aufbewahrungsklasse, für die [`-count n`] [`-duration m`] Sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.
** `-weekly` Ist die wöchentliche Aufbewahrungsklasse, für die [`-count n`] [`-duration m`] Sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.
** `-monthly` Ist die monatliche Aufbewahrungsklasse, für die [`-count n`] [`-duration m`] Sind die Anzahl der Aufbewahrung und die Aufbewahrungsdauer.




 a| 
*Sie möchten die E-Mail-Benachrichtigung für den Abschlussstatus der Datenbankvorgänge* aktivieren
 a| 
Geben Sie die folgenden Optionen und Variablen an:

** `-summary-notification` Ermöglicht die Konfiguration einer E-Mail-Benachrichtigung für mehrere Profile unter einer Repository-Datenbank.
** `-notification` Hiermit erhalten Sie eine E-Mail-Benachrichtigung über den Abschlussstatus des Datenbankvorgangs für ein Profil.
** `-success-emailemail_address2` Hiermit erhalten Sie eine E-Mail-Benachrichtigung über den erfolgreichen Datenbankvorgang, der mit einem neuen oder vorhandenen Profil durchgeführt wird.
** `-failure-emailemail_address2` Hiermit erhalten Sie eine E-Mail-Benachrichtigung über den fehlgeschlagenen Datenbankvorgang, der mit einem neuen oder vorhandenen Profil durchgeführt wird.
** `-subjectsubject_text` Gibt den Betreff für die E-Mail-Benachrichtigung an, während ein neues Profil oder ein vorhandenes Profil erstellt wird. Wenn die Benachrichtigungseinstellungen nicht für das Repository konfiguriert sind und Sie versuchen, mithilfe der CLI Profile- oder Übersichtsbenachrichtigungen zu konfigurieren, wird die folgende Meldung im Konsolenprotokoll protokolliert: `SMSAP-14577: Notification Settings not configured`.
+
Wenn Sie die Benachrichtigungseinstellungen konfiguriert haben und versuchen, eine zusammenfassende Benachrichtigung mithilfe der CLI zu konfigurieren, ohne eine zusammenfassende Benachrichtigung für das Repository zu aktivieren, wird die folgende Meldung im Konsole-Protokoll angezeigt: `SMSAP-14575: Summary notification configuration not available for this repository`





 a| 
*Sie wollen Archivprotokolldateien getrennt von Datendateien* sichern
 a| 
Geben Sie die folgenden Optionen und Variablen an:

** `-separate-archivelog-backups` Ermöglicht Ihnen die Trennung des Backup des Archivprotokolls von der Datendatei-Sicherung.
** `-retain-archivelog-backups` Legt die Aufbewahrungsdauer für Backups im Archivprotokoll fest. Sie müssen eine positive Aufbewahrungsdauer angeben.
+
Die Backups für das Archivprotokoll werden basierend auf der Aufbewahrungsdauer des Archivprotokolls aufbewahrt. Die Backups der Datendateien werden gemäß den bestehenden Aufbewahrungsrichtlinien beibehalten.

** `-include-with-online-backups` Umfasst das Backup des Archivprotokolls sowie das Online-Datenbank-Backup.
+
Mit dieser Option können Sie ein Backup- und Archivprotokoll für Online-Datendateien zum Klonen erstellen. Wenn diese Option eingestellt ist, werden bei jeder Erstellung eines Backups von Online-Datendateien die Archiv-Logs-Backups zusammen mit den Datendateien sofort erstellt.

** `-no-include-with-online-backups` Umfasst nicht das Backup des Archivprotokolls zusammen mit dem Datenbank-Backup.




 a| 
*Nach der erfolgreichen Profilerfassungsoperation* können Sie die Dump-Dateien sammeln
 a| 
Geben Sie die an `-dump` Option am Ende des `profile create` Befehl.

|===

