---
permalink: windows/task-update-the-existing-repository.html 
sidebar: sidebar 
keywords: update, exist, repository, upgrade, snapmanager, path 
summary: Sie müssen das vorhandene Repository nicht aktualisieren, wenn Sie ein Upgrade von SnapManager 3.3.x auf SnapManager 3.4 oder höher durchführen. Für alle anderen Upgrade-Pfade müssen Sie jedoch das vorhandene Repository aktualisieren, damit Sie nach dem Upgrade darauf zugreifen können. 
---
= Aktualisieren Sie das vorhandene Repository
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das vorhandene Repository nicht aktualisieren, wenn Sie ein Upgrade von SnapManager 3.3.x auf SnapManager 3.4 oder höher durchführen. Für alle anderen Upgrade-Pfade müssen Sie jedoch das vorhandene Repository aktualisieren, damit Sie nach dem Upgrade darauf zugreifen können.



== Was Sie benötigen

* Der aktualisierte SnapManager-Server muss gestartet und verifiziert worden sein.
* Ein Backup des vorhandenen Repositorys muss vorhanden sein.




== Über diese Aufgabe

* Wenn Sie ein Upgrade von einer älteren Version als SnapManager 3.1 auf SnapManager 3.3 oder höher durchführen, müssen Sie zuerst auf SnapManager 3.2 aktualisieren.
+
Nach dem Upgrade auf SnapManager 3.2 können Sie dann ein Upgrade auf SnapManager 3.3 oder höher durchführen.

* Nach dem Aktualisieren des Repositorys können Sie das Repository nicht mit einer früheren SnapManager-Version verwenden.


.Schritt
. Aktualisieren des vorhandenen Repositorys:
+
`*smsap repository update -repository -dbname _repository_service_name_ -host _repository_host_name_ -login -username _repository_user_name_ -port _repository_port_*`** Der Repository-Benutzername, der Repository-Dienstname und der Repository-Hostname können aus alphanumerischen Zeichen, einem Minuszeichen, einem Unterstrich und einem Zeitraum bestehen. ** Der Repository-Port kann eine beliebige gültige Portnummer sein. Die anderen Optionen, die beim Aktualisieren des vorhandenen Repositorys verwendet werden, sind wie folgt:

+
** Der `force` Option
** Der `noprompt` Option
** Der `quiet` Option
** Der `verbose` Option


+
*Beispiel*



[listing]
----
smsap repository update -repository -dbname HR1
-host server1 -login -username admin -port 1521
----


== Nachdem Sie fertig sind

Starten Sie den SnapManager-Server neu, um die zugehörigen Zeitpläne neu zu starten.
