---
permalink: windows/task-set-credentials-after-clearing-credential-cache.html 
sidebar: sidebar 
keywords: clear, cache, remove, store, user, credential, host, repository, repositories, profile, set 
summary: Nachdem Sie den Cache gelöscht haben, um die gespeicherten Benutzeranmeldeinformationen zu entfernen, können Sie die Anmeldeinformationen für die Hosts, Repositorys und Profile festlegen. 
---
= Legen Sie die Anmeldeinformationen fest, nachdem Sie den Anmeldeinformationscache gelöscht haben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie den Cache gelöscht haben, um die gespeicherten Benutzeranmeldeinformationen zu entfernen, können Sie die Anmeldeinformationen für die Hosts, Repositorys und Profile festlegen.



== Über diese Aufgabe

Sie müssen sicherstellen, dass Sie die gleichen Benutzeranmeldeinformationen für das Repository, den Profilhost und das Profil festlegen, das Sie zuvor angegeben haben. Beim Festlegen der Benutzeranmeldeinformationen wird eine verschlüsselte Anmeldedatei erstellt.

Die Anmeldedatei befindet sich unter `C:\Documents and Settings\Administrator\Application Data\NetApp\smsap\3.3.0`.

Führen Sie in der grafischen Benutzeroberfläche von SnapManager (GUI) die folgenden Schritte aus, wenn unter „Repositories“ kein Repository vorhanden ist:

.Schritte
. Klicken Sie auf *Tasks* > *vorhandenes Repository hinzufügen*, um ein vorhandenes Repository hinzuzufügen.
. Führen Sie die folgenden Schritte durch, um die Anmeldeinformationen für das Repository festzulegen:
+
.. Klicken Sie mit der rechten Maustaste auf das Repository und wählen Sie *Öffnen*.
.. Im `Repository Credentials Authentication` Geben Sie die Benutzeranmeldeinformationen ein.


. Führen Sie die folgenden Schritte durch, um die Anmeldeinformationen für den Host festzulegen:
+
.. Klicken Sie mit der rechten Maustaste auf den Host unter dem Repository und wählen Sie *Öffnen*.
.. Im `Host Credentials Authentication` Geben Sie die Benutzeranmeldeinformationen ein.


. Führen Sie die folgenden Schritte durch, um die Anmeldeinformationen für das Profil festzulegen:
+
.. Klicken Sie mit der rechten Maustaste auf das Profil unter dem Host und wählen Sie *Öffnen*.
.. Im `Profile Credentials Authentication` Geben Sie die Benutzeranmeldeinformationen ein.



