---
permalink: windows/task-configuring-e-mail-notification-for-an-existing-profile.html 
sidebar: sidebar 
keywords: updating, update, profile, configure, receive, email, notification, completion, database, operation, configuring, exist 
summary: Wenn Sie ein Profil aktualisieren, können Sie so konfigurieren, dass Sie eine E-Mail-Benachrichtigung über den Abschluss des Datenbankvorgangs erhalten. 
---
= Konfigurieren der E-Mail-Benachrichtigung für ein vorhandenes Profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein Profil aktualisieren, können Sie so konfigurieren, dass Sie eine E-Mail-Benachrichtigung über den Abschluss des Datenbankvorgangs erhalten.

* Sie müssen die E-Mail-Adresse konfigurieren, von der die Meldungen gesendet werden.
* Sie müssen eine einzelne E-Mail-Adresse oder mehrere E-Mail-Adressen eingeben, an die Benachrichtigungen gesendet werden.
+
Sie können eine kommagetrennte Liste für mehrere Adressen verwenden. Sie müssen sicherstellen, dass zwischen Komma und der nächsten E-Mail-Adresse kein Leerzeichen vorhanden ist. Optional können Sie auch einen Betreff zu der E-Mail hinzufügen.

+

NOTE: Sie müssen sicherstellen, dass Sie den Satz von mehreren E-Mail-Adressen in doppelte Anführungszeichen eingeben.



.Schritt
. Geben Sie den folgenden Befehl ein:
+
`smsap profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password db_password-port db_port]] [{-rman{-controlfile | {-login  -usernamerman_username-password  rman_password-tnsname  rman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][[ [ ]]| [[]] [-notification [-success-emailemail_address1,email_address2-subjectsubject_pattern] [-failure-emailemail_address1,email_address2-subjectsubject_pattern]]`

+
Mit der Option Erfolg erhalten Sie nur eine Benachrichtigung für erfolgreiche Datenbankvorgänge und die Ausfalloption, eine Benachrichtigung nur für fehlerhafte Datenbankvorgänge zu erhalten.


