---
permalink: windows/task-reset-profile-password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember 
summary: Sie können das Profilkennwort zurücksetzen, wenn Sie sich nicht an das Passwort erinnern, das Sie beim Erstellen des Profils angegeben haben. 
---
= Setzen Sie das Profilkennwort zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Profilkennwort zurücksetzen, wenn Sie sich nicht an das Passwort erinnern, das Sie beim Erstellen des Profils angegeben haben.



== Was Sie benötigen

* Sie müssen sicherstellen, dass der SnapManager-Server auf der Repository-Datenbank ausgeführt wird.
* Sie müssen über die lokalen Administratoranmeldedaten des Hosts verfügen, auf dem sich die Repository-Datenbank befindet.
* Sie müssen sicherstellen, dass das Profil nicht für einen Vorgang verwendet wird, wenn das Passwort für dieses Profil zurückgesetzt wird.




== Über diese Aufgabe

Sie können das Passwort entweder von der SnapManager-CLI oder von der GUI aus zurücksetzen. Beim Zurücksetzen des Passworts fragt SnapManager den SnapManager-Server auf dem Repository-Host ab, um das Betriebssystem für den Repository-Host zu identifizieren. Sie müssen die Anmeldeinformationen für den autorisierten Benutzer für die Verbindung zum Repository-Host eingeben. Der SnapManager-Server authentifiziert Benutzer mit ihren lokalen Administratoranmeldeinformationen auf der Repository-Datenbank. Wenn die Authentifizierung erfolgreich ist, setzt SnapManager das Profilkennwort auf dem SnapManager-Server mit dem neuen Passwort zurück.


NOTE: SnapManager führt den Verlauf der Vorgänge zum Zurücksetzen von Passwörtern nicht aus.

.Schritt
. Setzen Sie das Profilpasswort zurück, indem Sie den folgenden Befehl eingeben:
+
`*smsap password reset -profile _profile_ [-profile-password _profile_password_] [-repository-hostadmin-password _admin_password_]*`


