---
permalink: windows/task-customizing-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: Sie können den E-Mail-Betreff für das neue Profil anpassen, wenn Sie es erstellen. 
---
= Anpassen des E-Mail-Betreff für ein neues Profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den E-Mail-Betreff für das neue Profil anpassen, wenn Sie es erstellen.

Sie können den Betreff der E-Mail mithilfe des \{profile}_\{Operation-Name}_\{db-sid}_\{db-Host}_\{Startdatum}_\{Enddatum}_\{Status}-Musters anpassen oder Ihren eigenen Text eingeben.

|===
| Variablenname | Beschreibung | Beispielwert 


 a| 
Profil
 a| 
Profilname, der für den Datenbankvorgang verwendet wird
 a| 
PROF1



 a| 
Operation-Name
 a| 
Name des Datenbankvorgangs
 a| 
Backup, Daten-Backup, Daten- und Archivprotokolle Backup



 a| 
db-sid
 a| 
SID der Datenbank
 a| 
DB1



 a| 
db-Host
 a| 
Name des Hostservers
 a| 
Hosta



 a| 
Startdatum
 a| 
Startzeit der Datenbankoperation im Format mmdd:hh:ss yyyy
 a| 
April 27 21:00:45 PST 2012



 a| 
Enddatum
 a| 
Endzeit des Datenbankvorgangs im Format mmdd:hh:ss yyyy
 a| 
April 27 21:10:45 PST 2012



 a| 
Status
 a| 
Status des Datenbankvorgangs
 a| 
Erfolg

|===
Wenn Sie keinen Wert für die Variablen angeben, zeigt SnapManager die folgende Fehlermeldung an: Missing value(s) -subject.

. Geben Sie den folgenden Befehl ein:
+
`smsap profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][ [ ]] [-notification [-success-emailemail_address1,email_address2-subjectsubject_pattern] [-failure-emailemail_address1,email_address2-subjectsubject_pattern]]`


