---
permalink: windows/task-use-post-processing-task-specification-to-mirror-volumes.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, script, mirror, volume, backup, operation, windows, environment, post-process, task, specification 
summary: Mit SnapManager für SAP können Sie das Skript zur Spiegelung der Volumes verwenden, nachdem der Backup-Vorgang in einer Windows Umgebung durchgeführt wurde. 
---
= Verwenden Sie die Aufgabenspezifikation für die Nachbearbeitung, um Volumes zu spiegeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapManager für SAP können Sie das Skript zur Spiegelung der Volumes verwenden, nachdem der Backup-Vorgang in einer Windows Umgebung durchgeführt wurde.

.Schritte
. Erstellen Sie eine XML-Datei für die Aufgabenspezifikation.
. Geben Sie in der XML-Datei den Skriptnamen als Eingabeparameter ein.
. Speichern Sie die XML-Datei für die Aufgabenspezifikation.
. Erstellen Sie mit dem folgenden Befehl ein geschütztes Backup der Datenbank auf dem sekundären Speicher.
+
Beim Erstellen des geschützten Backups müssen Sie den vollständigen Pfad der XML-Datei für die gespeicherte Aufgabenspezifikation nach dem angeben -`taskspec` Option.

+
Beispiel: `smsapbackup create -profile test_profile -full -online -taskspec "C:\\mirror\\snapmirror.xml"`



Das folgende Beispiel zeigt eine Struktur für die Aufgabenspezifikation nach der Verarbeitung, wenn Sie Data ONTAP im 7-Mode verwenden:

[listing]
----
#     <post-tasks>
#               <task>
#                   <name>Mirror the backup</name>
#                    <description>Mirror the backup</description>
#               </task>
#             <post-tasks>
----
Das folgende Beispiel zeigt eine Struktur für die Aufgabenspezifikation nach der Verarbeitung, wenn Sie Clustered Data ONTAP verwenden:

[listing]
----
# <task-specification>
#              <post-tasks>
#                  <task>
#                   <name>"Vault the backup for cDOT"</name>
#                    <parameter>
#                    <name>SNAPSHOT_LABEL</name>
#                   <value>TST</value>
#                    </parameter>
#                  </task>
#                </post-tasks>
#              </task-specification>
#            </preposttask-specification>
----