---
permalink: windows/task-clear-user-credentials-for-all-hosts-repositories-and-profiles.html 
sidebar: sidebar 
keywords: clear, cache, credential, resource, host, repository, repositories, profile, delete, authenticate, host 
summary: 'Sie können den Cache Ihrer Anmeldeinformationen für Ressourcen (Hosts, Repositorys und Profile) löschen. Dadurch werden alle Ressourcen-Anmeldeinformationen für den Benutzer gelöscht, der den Befehl ausführt. Nach dem Löschen des Cache müssen Sie Ihre Anmeldeinformationen erneut authentifizieren, um auf diese gesicherten Ressourcen zugreifen zu können.' 
---
= Löschen Sie die Benutzeranmeldeinformationen für alle Hosts, Repositorys und Profile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Cache Ihrer Anmeldeinformationen für Ressourcen (Hosts, Repositorys und Profile) löschen. Dadurch werden alle Ressourcen-Anmeldeinformationen für den Benutzer gelöscht, der den Befehl ausführt. Nach dem Löschen des Cache müssen Sie Ihre Anmeldeinformationen erneut authentifizieren, um auf diese gesicherten Ressourcen zugreifen zu können.

.Schritte
. Um Ihre Anmeldeinformationen zu löschen, geben Sie das ein `smsap credential clear` Befehl aus der SnapManager CLI oder wählen Sie *Admin* > *Anmeldeinformationen* > *Cache löschen* aus der SnapManager-Benutzeroberfläche.
. Schließen Sie die SnapManager-Benutzeroberfläche.
+
[NOTE]
====
** Wenn Sie den Anmeldeinformationscache von der SnapManager-GUI gelöscht haben, müssen Sie die SnapManager-Benutzeroberfläche nicht beenden.
** Wenn Sie den Anmeldeinformationscache von der SnapManager-CLI gelöscht haben, müssen Sie die SnapManager-GUI neu starten.
** Wenn Sie die verschlüsselte Anmeldedatei manuell gelöscht haben, müssen Sie die SnapManager-GUI erneut starten.


====
. Um die Anmeldeinformationen erneut festzulegen, wiederholen Sie den Vorgang, um die Anmeldeinformationen für das Repository, den Profilhost und das Profil festzulegen. Weitere Informationen zum erneuten Einstellen der Benutzeranmeldeinformationen finden Sie unter „Anmeldeinformationen nach dem Löschen des Anmeldeinformationscache festlegen“.

