---
permalink: windows/task-add-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command, add 
summary: Nachdem Sie eine E-Mail-Benachrichtigung für die Repository-Datenbank konfiguriert haben, können Sie mithilfe des Befehls Summary Notification ein neues Profil zur zusammenfassenden Benachrichtigung hinzufügen. 
---
= Fügen Sie ein neues Profil zu E-Mail-Benachrichtigungen hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie eine E-Mail-Benachrichtigung für die Repository-Datenbank konfiguriert haben, können Sie mithilfe der ein neues Profil zur zusammenfassenden Benachrichtigung hinzufügen `summary notification` Befehl.

.Schritt
. Geben Sie den folgenden Befehl ein:
+
`*smsap profile create -profile _profile_name_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login- username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] [-retain [-hourly -count _n_] [-duration _m_]] [-daily -count _n_] [-duration _m_]] [-weekly -count _n_] [-duration _m_]] [-monthly -count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][ [ ]] [-summary-notification]*`

+
Weitere Optionen für diesen Befehl:

+
[`-force`]

+
[`quiet` . `-verbose`]


