---
permalink: windows/task-configure-e-mail-notification-for-a-new-profile.html 
sidebar: sidebar 
keywords: create, profile, configure, receive, email, notification, completion, database, operation, profile 
summary: Wenn Sie ein neues Profil erstellen, können Sie so konfigurieren, dass Sie eine E-Mail-Benachrichtigung nach Abschluss des Datenbankvorgangs erhalten. 
---
= Konfigurieren Sie die E-Mail-Benachrichtigung für ein neues Profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein neues Profil erstellen, können Sie so konfigurieren, dass Sie eine E-Mail-Benachrichtigung nach Abschluss des Datenbankvorgangs erhalten.



== Was Sie benötigen

* Sie müssen die E-Mail-Adresse konfigurieren, von der die Meldungen gesendet werden.
* Sie müssen eine kommagetrennte Liste für mehrere E-Mail-Adressen verwenden.
+
Sie müssen sicherstellen, dass zwischen Komma und der nächsten E-Mail-Adresse kein Leerzeichen vorhanden ist.

+

NOTE: Sie müssen sicherstellen, dass Sie den Satz von E-Mail-Adressen in doppelte Anführungszeichen eingeben.



.Schritt
. Geben Sie den folgenden Befehl ein:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [ ]][-notification [-success-email _email_address1_,_email_address2_ -subject _subject_pattern_] [-failure -email _email_address1_,_email_address2_ -subject _subject_pattern_]]*`

+
Weitere Optionen für diesen Befehl:

+
[`-force`]

+
[`quiet` . `-verbose`]

+

NOTE: SnapManager unterstützt bis zu 1000 Zeichen für E-Mail-Adressen.

+
Wenn Sie mithilfe des Profils (zur Erstellung separater Archiv-Log-Backups) eine Sicherung von Datendateien und Archivprotokolldateien erstellen und die Erstellung der Datendatei-Sicherung fehlschlägt, wird die E-Mail-Benachrichtigung mit der Datensicherung als Operationname anstatt Datensicherung und Archivprotokolle als Backup gesendet. Wenn die Datensicherung der Datendatei und der Archivprotokolldatei erfolgreich ist, wird die Ausgabe wie folgt angezeigt:

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----

