---
permalink: unix-administration/concept-managing-profiles-for-efficient-backups.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, database, operation, manage, managing, efficient 
summary: Sie müssen in SnapManager ein Profil für die Datenbank erstellen, auf der Sie einen Vorgang ausführen möchten. Sie müssen das Profil auswählen und dann den Vorgang auswählen, den Sie durchführen möchten. 
---
= Profilverwaltung für effiziente Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen in SnapManager ein Profil für die Datenbank erstellen, auf der Sie einen Vorgang ausführen möchten. Sie müssen das Profil auswählen und dann den Vorgang auswählen, den Sie durchführen möchten.



== Aufgaben im Zusammenhang mit Profilen

Sie können die folgenden Aufgaben ausführen:

* Erstellung von Profilen für vollständige oder teilweise Backups und Backups auf primärem, sekundärem oder gar tertiärem Storage
+
Sie können auch Profile erstellen, um die Archiv-Log-Backups von den Backups der Datendatei zu trennen.

* Verifizieren von Profilen:
* Profile aktualisieren.
* Profile löschen.




== Info zu Profilen und Authentifizierung

Wenn Sie ein Profil erstellen, können Sie eine Datenbank angeben und eine der folgenden Methoden zur Verbindung mit der Datenbank auswählen:

* Oracle-Authentifizierung mit Benutzername, Passwort und Port
* Betriebssystemauthentifizierung (OS) ohne Benutzername, Passwort oder Port
+
Für die OS-Authentifizierung müssen Sie die Informationen für den OS-Kontobenutzer und -Gruppen eingeben.

+

NOTE: Um die OS-Authentifizierung für die RAC-Datenbanken (Real Application Cluster) zu verwenden, muss der SnapManager-Server auf jedem Knoten der RAC-Umgebung ausgeführt werden. Das Datenbankkennwort muss für alle Oracle-Instanzen in einer RAC-Umgebung identisch sein. SnapManager verwendet den Datenbankbenutzernamen und das Kennwort, um eine Verbindung zu jeder RAC-Instanz im Profil herzustellen.

* Datenbankauthentifizierung, wenn `sqlnet.authentication_services` Ist auf festgelegt `*NONE*`. SnapManager verwendet dann für alle Verbindungen zur Zieldatenbank den Datenbankbenutzernamen und das Kennwort.
+

NOTE: Um die Datenbankauthentifizierung für eine ASM-Instanz (Automatic Storage Management) zu verwenden, müssen Sie den Benutzernamen und das Kennwort eingeben, mit dem Sie sich bei der ASM-Instanz anmelden.



Sie können festlegen `sqlnet.authentication_services` Bis `*NONE*` Nur in den folgenden Umgebungen:

[cols="1a,1a,1a,1a"]
|===
| Datenbank-Layout | Oracle Version | Wird die Datenbankauthentifizierung für die Zieldatenbank unterstützt | Wird die Datenbankauthentifizierung für die ASM-Instanz unterstützt 


 a| 
Alle nicht-ASM- und nicht-RAC-Datenbanken
 a| 
Oracle 10g und Oracle 11g (weniger als 11.2.0.3)
 a| 
Ja.
 a| 
Nein



 a| 
Eigenständige ASM-Datenbank auf UNIX
 a| 
Oracle 11.2.0.3 und höher
 a| 
Ja.
 a| 
Ja.



 a| 
ASM-Instanz auf RAC-Datenbank auf UNIX
 a| 
Oracle 11.2.0.3
 a| 
Nein
 a| 
Nein



 a| 
RAC Datenbank auf NFS
 a| 
Oracle 11.2.0.3
 a| 
Ja.
 a| 
Nein

|===

NOTE: Nach dem Deaktivieren von `sqlnet.authentication_services` Und ändern Sie die Authentifizierungsmethode in die Datenbankauthentifizierung, müssen Sie festlegen `sqlnet.authentication_services` Bis `*NONE*`.

Wenn Sie zum ersten Mal auf ein Profil zugreifen, müssen Sie Ihr Profilkennwort eingeben. Nachdem Sie Ihre Anmeldedaten eingegeben haben, können Sie die Datenbank-Backups im Profil anzeigen.
