---
permalink: unix-administration/concept-backing-up-and-restoring-files-using-br-tools.html 
sidebar: sidebar 
keywords: addition, backing, up, database, file, br, tools, back, restore, sap, system, storage 
summary: Zusätzlich zum Sichern von Datenbankdateien können Sie mit BR*Tools alle Dateien, wie z. B. die auf dem Speichersystem gespeicherten SAP-Systemdateien, sichern und wiederherstellen 
---
= Sichern und Wiederherstellen von Dateien mit BR*Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zusätzlich zum Sichern von Datenbankdateien können Sie mit BR*Tools alle Dateien, wie z. B. die auf dem Speichersystem gespeicherten SAP-Systemdateien, sichern und wiederherstellen.

Folgen Sie der Dokumentation zu SAP BR*Tools für die Befehle BRBACKUP und BRRESTORE. Die folgenden zusätzlichen Informationen gelten für die Verwendung von SnapManager für SAP:

* Die Dateien müssen auf dem Speichersystem gespeichert werden.
* Stellen Sie sicher, dass Sie über die Berechtigungen für die Dateien verfügen, die Sie sichern. Beispielsweise sollten Sie SAP Systemdateien sichern (`BRBACKUP backup_mode=sap_dir`) Oder Oracle Systemdateien (`BRBACKUP backup_mode=ora_dir`) Erfordert Root-Berechtigung auf dem Host. Verwenden Sie den Befehl su root, bevor Sie BRBACKUP ausführen.

