---
permalink: unix-administration/concept-what-snapmanager-database-backups-are.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, backup, task, assign, retention, class, retain, reach, database 
summary: SnapManager ermöglicht Ihnen die Durchführung verschiedener Backup-Aufgaben. Sie können Aufbewahrungsklassen zuweisen, um festzulegen, wie lange das Backup aufbewahrt werden kann. Sobald diese Frist erreicht ist, wird das Backup gelöscht. 
---
= Welche SnapManager Datenbank-Backups sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager ermöglicht Ihnen die Durchführung verschiedener Backup-Aufgaben. Sie können Aufbewahrungsklassen zuweisen, um festzulegen, wie lange das Backup aufbewahrt werden kann. Sobald diese Frist erreicht ist, wird das Backup gelöscht.

* Erstellen von Backups auf dem primären Storage
* Erstellen geschützter Backups auf den sekundären Speicherressourcen
* Überprüfen Sie, ob die Backups erfolgreich abgeschlossen wurden
* Zeigen Sie eine Liste von Backups an
* Planen Sie Backups über die grafische Benutzeroberfläche
* Verwalten Sie die Anzahl der beibehaltenen Backups
* Kostenlose Backup-Ressourcen
* Mounten und unmounten Sie Backups
* Backups löschen


SnapManager erstellt Backups mithilfe einer der folgenden Aufbewahrungsklassen:

* Stündlich
* Täglich
* Wöchentlich
* Monatlich
* Unbegrenzt


Der Protection Manager muss installiert werden, um Sicherungsrichtlinien für den Schutz von Backups zu verwenden. Ein Backup kann einen dieser Schutzzustände haben: Nicht angefordert, nicht geschützt oder geschützt.

Wenn neue Datendateien zur Datenbank hinzugefügt werden, sollten Sie sofort eine neue Sicherung erstellen. Wenn Sie außerdem ein Backup wiederherstellen, das vor dem Hinzufügen der neuen Datendateien erstellt wurde, und versuchen Sie, es nach dem Hinzufügen der neuen Datendateien zu einem Punkt wiederherzustellen, kann der automatische Recovery-Prozess fehlschlagen. Weitere Informationen zum Prozess zur Wiederherstellung der nach einem Backup hinzugefügten Datendateien finden Sie in der Oracle-Dokumentation.
