---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: 'Die Sicherheit in SnapManager lässt sich durch Benutzerauthentifizierung und rollenbasierte Zugriffssteuerung (Role Based Access Control, RBAC) managen. Die Benutzerauthentifizierungsmethode ermöglicht den Zugriff auf Ressourcen wie Repositorys, Hosts und Profile. RBAC ermöglicht Ihnen, die Vorgänge, die SnapManager für die Volumes und LUNs ausführen kann, die die Datendateien in der Datenbank enthalten, einzuschränken.' 
---
= Sicherheits- und Anmeldeinformationsmanagement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Sicherheit lässt sich in SnapManager unter Verwendung von Benutzerauthentifizierungund rollenbasierter Zugriffssteuerung (Role Based Access Control, RBAC) managen. Die Benutzerauthentifizierungsmethode ermöglicht den Zugriff auf Ressourcen wie Repositorys, Hosts und Profile. RBAC ermöglicht Ihnen, die Vorgänge, die SnapManager für die Volumes und LUNs ausführen kann, die die Datendateien in der Datenbank enthalten, einzuschränken.

Wenn Sie einen Vorgang über die Befehlszeilenschnittstelle (CLI) oder die grafische Benutzeroberfläche (GUI) ausführen, ruft SnapManager die für Repositorys und Profile festgelegten Anmeldeinformationen ab. SnapManager speichert Anmeldeinformationen früherer Installationen.

Das Repository und die Profile können mit einem Passwort gesichert werden. Eine Anmeldeinformationen ist das für den Benutzer für ein Objekt konfigurierte Passwort, und das Passwort ist nicht für das Objekt selbst konfiguriert.

Sie können die Authentifizierung und Anmeldeinformationen verwalten, indem Sie die folgenden Aufgaben ausführen:

* Verwalten Sie die Benutzerauthentifizierung entweder durch Eingabeaufforderungen für Passwörter für Vorgänge oder mithilfe des `smsap credential set` Befehl.
+
Legen Sie Anmeldedaten für ein Repository, einen Host oder ein Profil fest.

* Zeigen Sie die Anmeldeinformationen an, die die Ressourcen regeln, auf die Sie Zugriff haben.
* Löschen Sie die Anmeldeinformationen eines Benutzers für alle Ressourcen (Hosts, Repositorys und Profile).
* Löschen Sie die Anmeldeinformationen eines Benutzers für einzelne Ressourcen (Hosts, Repositorys und Profile).


Sie können rollenbasierten Zugriff verwalten, indem Sie die folgenden Aufgaben ausführen:

* RBAC für SnapManager wird mithilfe von SnapDrive aktiviert.
* Weisen Sie Benutzer über die Operations Manager-Konsole Rollen zu und legen Sie Rollenfunktionen fest.
* Aktivieren Sie optional SnapManager zum Speichern verschlüsselter Passwörter, indem Sie den bearbeiten `smsap.config file`.


Wenn Protection Manager installiert ist, wird der Zugriff auf die Funktionen wie folgt beeinträchtigt:

* Falls Protection Manager installiert ist, erstellt SnapManager bei der Erstellung eines Datenbankprofils einen Datensatz und füllt den Datensatz mit den Volumes aus, die die Datenbankdateien enthalten.
+
Nach einem Backup-Vorgang synchronisiert SnapManager den Datensatz mithilfe der Datenbankdateien.

* Wenn Protection Manager nicht installiert ist, kann SnapManager keinen Datensatz erstellen und Sie können keinen Schutz für Profile festlegen.

