---
permalink: unix-administration/reference-the-smosmsapprofile-sync-command.html 
sidebar: sidebar 
keywords: command, load, profile-to-repository, mappings, repository, file, home, directory, local, host, smsap 
summary: Mit diesem Befehl werden die Profile-to-Repository-Zuordnungen für dieses Repository in eine Datei im Home-Verzeichnis auf dem lokalen Host geladen. 
---
= Der Befehl smsap profile SYNC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl werden die Profile-to-Repository-Zuordnungen für dieses Repository in eine Datei im Home-Verzeichnis auf dem lokalen Host geladen.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap profile sync
-repository
-dbname _repo_service_name_
-host _repo_host_
-port _repo_port_
-login
-username _repo_username_                  [-quiet | -verbose]]
----


== Parameter

* ``*-repository*``
+
Die Optionen, die dem -Repository folgen, geben die Details der Datenbank für das Repository an.

* ``*-dbname _repo_service_name_*``
+
Gibt die Repository-Datenbank für das zu synchronisierende Profil an.

* ``*-host*``
+
Gibt den Datenbank-Host an.

* ``*-port*``
+
Gibt den Port für den Host an.

* ``*-login*``
+
Gibt den Anmeldeprozess für den Hostbenutzer an.

* ``*-username*``
+
Gibt den Benutzernamen für den Host an.

* ``*-quiet*``
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* ``*-verbose*``
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl

Das folgende Beispiel zeigt das Ergebnis des Befehls zum Synchronisieren der Profile-zu-Repository-Zuordnungen für die Datenbank.

[listing]
----
smsap profile sync -repository -dbname smrepo -host Host2 -port 1521 -login -username user2
SMSAP-12345 [INFO ]: Loading profile mappings for repository "user2@Host2:smrepo" into cache for OS User "admin".
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----