---
permalink: unix-administration/reference-copyright.html 
sidebar: sidebar 
keywords: copyright 
summary: Urheberrecht 
---
= Urheberrecht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


© 2019 NetApp. Alle Rechte vorbehalten. Gedruckt in den USA

Dieses urheberrechtlich geschützte Dokument darf ohne die vorherige schriftliche Genehmigung des Urheberrechtsinhabers in keiner Form und durch keine Mittel- weder grafische noch elektronische oder mechanische, einschließlich Fotokopieren, Aufnehmen, Verkleben oder Speichern in einem elektronischen Abrufsystem - ohne vorherige schriftliche Genehmigung des Urheberrechtsinhabers.

Software, die von urheberrechtlich geschütztem NetApp Material abgeleitet wird, unterliegt der folgenden Lizenz und dem folgenden Haftungsausschluss:

DIE VORLIEGENDE SOFTWARE WIRD IN DER VORLIEGENDEN FORM VON NETAPP ZUR VERFÜGUNG GESTELLT, D. H. OHNE JEGLICHE EXPLIZITE ODER IMPLIZITE GEWÄHRLEISTUNG, EINSCHLIESSLICH, JEDOCH NICHT BESCHRÄNKT AUF DER STILLSCHWEIGENDEN GEWÄHRLEISTUNG DER MARKTGÄNGIGKEIT UND EIGNUNG FÜR EINEN BESTIMMTEN ZWECK, DIE HIERMIT AUSGESCHLOSSEN WERDEN. NETAPP ÜBERNIMMT KEINERLEI HAFTUNG FÜR DIREKTE, INDIREKTE, ZUFÄLLIGE, BESONDERE ODER FOLGESCHÄDEN (EINSCHLIESSLICH, JEDOCH NICHT BESCHRÄNKT AUF DIE BESCHAFFUNG ODER DEN ERSATZ VON WAREN ODER DIENSTLEISTUNGEN, NUTZUNGS-, DATEN- ODER GEWINNVERLUST, ODER BETRIEBSUNTERBRECHUNG) JEDOCH VERURSACHT UND AUF JEDE ART VON HAFTUNG, OB VERTRAGLICH, STRENG HAFTBAR ODER SOFORT (EINSCHLIESSLICH FAHRLÄSSIGKEIT ODER AUF ANDERE WEISE), DIE IN IRGENDEINER WEISE AUS DER NUTZUNG DIESER SOFTWARE, AUCH WENN AUF DIE MÖGLICHKEIT EINES SOLCHEN SCHADENS HINGEWIESEN.

NetApp behält sich das Recht vor, die hierin beschriebenen Produkte jederzeit und ohne Vorankündigung zu ändern. NetApp übernimmt keine Verantwortung oder Haftung für die Verwendung der hier beschriebenen Produkte, sofern nicht ausdrücklich in schriftlicher Form von NetApp angegeben. Die Verwendung oder der Erwerb dieses Produkts stellt keine Lizenzierung im Rahmen eines Patentrechts, Markenrechts oder eines anderen Rechts an geistigem Eigentum von NetApp dar.

Das in diesem Handbuch beschriebene Produkt kann durch ein oder mehrere US-amerikanische Patente, ausländische Patente oder Patentanmeldungen geschützt sein.

Die hierin enthaltenen Daten beziehen sich auf ein kommerzielles Produkt (wie in FAR 2.101 definiert) und sind Eigentum von NetApp, Inc. Die USA Regierung besitzt eine nicht ausschließliche, nicht übertragbare, nicht sublizenzierbare, weltweite, limitierte unwiderrufliche Lizenz, die Daten nur in Verbindung mit und ausgehend von den USA zu verwenden Regierung zu nutzen, in dessen Rahmen die Daten bereitgestellt wurden. Sofern in diesem Dokument nicht angegeben, dürfen die Daten nicht verwendet, offengelegt, reproduziert, geändert, ausgeführt, Oder angezeigt ohne vorherige schriftliche Genehmigung von NetApp Inc. Die Lizenzrechte der US-Regierung für das US-Verteidigungsministerium beschränken sich auf die Rechte, die in DFARS Absatz 252.227-7015(b) zu finden sind.
