---
permalink: unix-administration/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credentials, secure, resource, smsap 
summary: Mit diesem Befehl werden die Benutzeranmeldeinformationen für eine bestimmte gesicherte Ressource gelöscht. 
---
= Der Befehl smsap Anmeldeinformation löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl werden die Benutzeranmeldeinformationen für eine bestimmte gesicherte Ressource gelöscht.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap credential delete
[-host -name _host_name_
-username _username_\] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_\] |
[-profile
-name _profile_name_\]
[-quiet | -verbose]]
----


== Parameter

* `*-host _hostname_*`
+
Gibt den Namen des Host-Servers an, auf dem SnapManager ausgeführt wird.

+
Der `-host` Parameter enthält die folgenden Optionen:

+
** `-name _host_name_`: Gibt den Namen des Hosts an, für den Sie das Passwort löschen möchten.
** `-username _user_name_`: Gibt den Benutzernamen auf dem Host an.


* `*-repository -dbname*`
+
Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

+
Der `-repository` Parameter enthält die folgenden Optionen:

+
** `-dbname _repo_service_name_`: Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.
** `-host _repo_host_`: Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem die Repository-Datenbank ausgeführt wird.
** `-login-username _repo_username_`: Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank benötigt wird, in der das Repository gespeichert ist.
** `-port _repo_port_`: Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.


* `*-profile -name _profile_name_*`
+
Gibt das Profil an, mit dem die Datenbank verknüpft ist.

+
Der `-profile` Parameter enthält die folgende Option:

+
** `-name _profilename_`: Gibt den Namen des Profils an, für das Sie das Passwort löschen möchten.


* `*-quiet*`
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* `*-verbose*`
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.



'''


== Beispielbefehl

In diesem Beispiel werden die Anmeldeinformationen des Profils gelöscht.

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
In diesem Beispiel werden die Anmeldeinformationen des Repositorys gelöscht.

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
In diesem Beispiel werden die Anmeldeinformationen des Hosts gelöscht.

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
'''