---
permalink: unix-administration/reference-the-smosmsap-operation-show-command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, output, client, user, snapmanager, host, smsap 
summary: 'Sie können den Befehl „Operation show“ ausführen, um die Zusammenfassungsinformationen aller Vorgänge, die für das angegebene Profil durchgeführt wurden, aufzulisten. Die Ausgabe listet den Client-Benutzer (den Benutzer für den Client-PC) und den effektiven Benutzer (den Benutzer in SnapManager, der auf dem ausgewählten Host gültig ist) auf.' 
---
= Befehl smsap Operation show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Befehl „Operation show“ ausführen, um die Zusammenfassungsinformationen aller Vorgänge, die für das angegebene Profil durchgeführt wurden, aufzulisten. Die Ausgabe listet den Client-Benutzer (den Benutzer für den Client-PC) und den effektiven Benutzer (den Benutzer in SnapManager, der auf dem ausgewählten Host gültig ist) auf.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap operation show
-profile _profile_name_
[-label _label_ | -id _id_\] [-quiet | -verbose\]]
----


== Parameter

* `*-profile _profile_name_*`
+
Gibt den Namen des Profils an. Dieser Name kann bis zu 30 Zeichen lang sein und muss innerhalb des Hosts eindeutig sein.

* `*-label _label_*`
+
Gibt die Bezeichnung für den Vorgang an.

* `*-id _id_*`
+
Gibt die Kennung für den Vorgang an.

* `*-quiet*`
+
Optional: Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* `*-verbose*`
+
Optional: Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an.



'''


== Beispiel

In der folgenden Befehlszeile werden detaillierte Informationen über einen Vorgang angezeigt:

[listing]
----
smsap operation show -id 8ac861781d0ac992011d0ac999680001  -profile CER
----
[listing]
----
Operation Attempted
    Operation ID: 8ac861781d0ac992011d0ac999680001
    Type:Backup
    For profile: CER
    With Force: No
    Label: 081017180043
    Comments: BRBACKUP
Operation Runtime Information
   Status: SUCCESS
   Start date: 2008-10-16 18:01:00 IST
   End date: 2008-10-17 18:01:26 IST
   Client user: oracle
   Effective user: oracle
   By schedule: none
Host
   Host Run upon: lnx225-248.lab.eng.org.com
   Process ID: 29096
   SnapManager version: 3.3
Repository
   Connection: krishna@smsaprep/10.72.225.155:1521
   Repository version: 62
Error messages
   The operation did not generate any error messages.
Resources in use
   Snapshots:
      f270-225-57:/vol/f270_lnx225_248_10gr2_sap_oracle_cer:smsap_cer_cer1_f_c_2_8ac861781d0ac992011d0ac999680001_0
   Storage components:
    /sapbackup/backCER1.log (File)
    /sapbackup/bdzbalta.anf (File)
    /sapreorg/spaceCER1.log (File)
    /mnt/oracle/CER (File System)
    ...
----
'''