---
permalink: unix-administration/reference-the-smosmsapbackup-create-command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smsap 
summary: Sie können den Befehl Backup create ausführen, um Datenbank-Backups auf einem oder mehreren Speichersystemen zu erstellen. 
---
= Der Befehl smsap Backup erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ausführen `backup create` Befehl zum Erstellen von Datenbank-Backups auf einem oder mehreren Speichersystemen.



== Syntax


NOTE: Bevor Sie diesen Befehl ausführen, müssen Sie ein Datenbankprofil mithilfe des Befehls Profile create erstellen erstellen.

[listing, subs="+macros"]
----
pass:quotes[smsap backup create
-profile profile_name
{[-full{-auto | -online | -offline} [-retain {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-unlimited_} [-verify\]  |
[-data [[-files _files_ [_files_]] |
pass:quotes[[-tablespaces _tablespaces_ [_tablespaces_]] pass:quotes[[-label _label_]] {-auto | -online | -offline}
pass:quotes[[-retain {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-unlimited_} [-verify] |
pass:quotes[[-archivelogs [-label _label_]] pass:quotes[[-comment _comment_\]}
[-protect | -noprotect | -protectnow\]
[-backup-dest _path1_ [ _, path2_\]\]
[-exclude-dest path1 [ _, path2_\]\]
[-prunelogs {-all | -until-scn _until-scn_ | -until-date _yyyy-MM-dd:HH:mm:ss_\] | -before {-months | -days | -weeks | -hours}}
-prune-dest _prune_dest1_,[_prune_dest2_\]\]
[-taskspec _taskspec_\]
[-dump]-force
[-quiet | -verbose]]
----


== Parameter

* `*-profile _profile_name_*`
+
Gibt den Namen des Profils an, das mit der Datenbank verknüpft ist, die gesichert werden soll. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* `*-auto*` *Option*
+
Wenn die Datenbank im Status „angehängt“ oder „Offline“ steht, führt SnapManager ein Offline-Backup durch. Wenn sich die Datenbank im offenen oder Online-Status befindet, führt SnapManager ein Online-Backup durch. Wenn Sie den verwenden `-force` Option mit dem `-offline` Option, SnapManager erzwingt ein Offline-Backup, selbst wenn die Datenbank derzeit online ist.

* `*-online*` *Option*
+
Gibt ein Online-Datenbank-Backup an.

+
Sie können ein Online-Backup einer RAC-Datenbank (Real Application Clusters) erstellen, solange sich der primäre Status im offenen Zustand befindet oder der primäre Server gemountet ist und sich eine Instanz im offenen Zustand befindet. Sie können das verwenden `-force` Option für Online-Backups, wenn sich die lokale Instanz im Shutdown-Status befindet oder sich keine Instanz im offenen Status befindet. Die Version von Oracle muss 10.2.0.5 sein. Andernfalls wird die Datenbank hängen, wenn eine Instanz im RAC eingebunden ist.

+
** Wenn sich die lokale Instanz im Herunterfahren befindet und mindestens eine Instanz im offenen Zustand befindet, können Sie die verwenden `-force` Option zum Ändern der lokalen Instanz in den angehängten Status.
** Wenn sich keine Instanz im Status „Open“ befindet, können Sie die Option „-Force“ verwenden, um die lokale Instanz in den Status „Open“ zu ändern.


* `*-offline*` *Option*
+
Gibt ein Offline-Backup an, während sich die Datenbank im Status Herunterfahren befindet. Wenn sich die Datenbank im offenen oder gemounteten Status befindet, schlägt das Backup fehl. Wenn der `-force` Die Option wird verwendet, versucht SnapManager, den Datenbankstatus zu ändern, um die Datenbank für ein Offline-Backup herunterzufahren.

* `*-full*` *Option*
+
Sicherung der gesamten Datenbank. Dazu gehören alle Daten, archivierte Log- und Kontrolldateien. Die archivierten Wiederherstellungsprotokolle und Kontrolldateien werden gesichert, unabhängig davon, welche Art von Backup Sie durchführen. Wenn Sie nur einen Teil der Datenbank sichern möchten, verwenden Sie den `-files` Option oder `-tablespaces` Option.

* `*-data*` *Option*
+
Gibt die Datendateien an.

* `*-files _list_*`
+
Sichert nur die angegebenen Datendateien sowie die archivierten Protokoll- und Kontrolldateien. Trennen Sie die Liste der Dateinamen mit Leerzeichen. Wenn die Datenbank offen ist, überprüft SnapManager, ob sich die entsprechenden Tabellen im Online-Backup-Modus befinden.

* `*-tablespaces _tablespaces_*`
+
Sicherung nur der angegebenen Datenbanktablespaces plus der archivierten Protokoll- und Kontrolldateien Trennen Sie die Namen der Tablespaces durch Leerzeichen. Wenn die Datenbank offen ist, überprüft SnapManager, ob sich die entsprechenden Tabellen im Online-Backup-Modus befinden.

* `*-label _label_*`
+
Gibt einen optionalen Namen für dieses Backup an. Dieser Name muss innerhalb des Profils eindeutig sein. Der Name kann Buchstaben, Zahlen, Unterstriche (_) und Bindestriche (-) enthalten. Es kann nicht mit einem Bindestrich beginnen. Wenn Sie keine Beschriftung angeben, erstellt SnapManager im Scope_type_date-Format eine Standardbeschriftung:

+
** Der Umfang ist entweder F, um ein vollständiges Backup anzuzeigen, oder P, um auf ein teilweises Backup hinzuweisen.
** Geben Sie C ein, um ein Offline-Backup (Cold) anzuzeigen, H für ein Online-Backup (Hot) oder Ein Für die automatische Sicherung, z. B. P_A_20081010060037IST, anzuzeigen.
** Datum ist Jahr, Monat, Tag und Uhrzeit des Backups.
+
SnapManager verwendet eine 24-Stunden-Zeit.



+
Beispiel: Wenn Sie am 16. Januar 2007 um 5:45:16 Uhr eine vollständige Sicherung mit offline der Datenbank durchgeführt haben Eastern Standard Time, SnapManager würde die Bezeichnung F_C_20070116174516EST erstellen.

* `*-comment _string_*`
+
Gibt einen optionalen Kommentar an, um dieses Backup zu beschreiben. Schließen Sie die Zeichenfolge in einzelne Anführungszeichen (').

+

NOTE: Einige Schalen entfernen die Anführungszeichen. In diesem Fall müssen Sie das Anführungszeichen mit einem umgekehrten Schrägstrich (\) angeben. Möglicherweise müssen Sie Folgendes eingeben: `\' this is a comment\'`.

* `*-verify*` *Option*
+
Überprüft, ob die Dateien im Backup nicht beschädigt sind, indem Sie das Oracle dbv-Dienstprogramm ausführen.

+

NOTE: Wenn Sie den angeben `-verify` Option: Der Sicherungsvorgang wird erst abgeschlossen, wenn der Überprüfungvorgang abgeschlossen ist.

* `*-force*` *Option*
+
Erzwingt eine Statusänderung, wenn sich die Datenbank nicht im richtigen Zustand befindet. Beispielsweise kann SnapManager den Status der Datenbank von Online- in Offline-Modus ändern, basierend auf dem von Ihnen angegebenen Backup-Typ und dem Status, in dem sich die Datenbank befindet.

+
Verwenden Sie bei einer Online-Sicherung von RAC-Datenbanken die `-force` Option, wenn sich die lokale Instanz im Shutdown-Status befindet oder sich keine Instanz im offenen Status befindet.

+

NOTE: Die Version von Oracle muss 10.2.0.5 sein. Andernfalls wird die Datenbank hängen, wenn eine Instanz im RAC eingebunden ist.

+
** Wenn sich die lokale Instanz im Shutdown-Status befindet und sich mindestens eine Instanz im offenen Zustand befindet, verwenden Sie die `-force` Mit dieser Option wird die lokale Instanz in den angehängten Status geändert.
** Wenn sich keine Instanz im Status „offen“ befindet, verwenden Sie die `-force` Mit dieser Option wird die lokale Instanz in den Status „Öffnen“ geändert.


* `*-quiet*`
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* `*-verbose*`
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an.

* `*-protect | -noprotect | -protectnow*`
+
Gibt an, ob das Backup auf sekundärem Storage gesichert werden soll. Die Option -noprotect gibt an, dass das Backup nicht auf einem sekundären Speicher geschützt werden soll. Nur vollständige Backups sind gesichert. Wenn keine Option angegeben wird, schützt SnapManager das Backup standardmäßig, wenn es sich bei dem Backup um ein vollständiges Backup handelt, und das Profil eine Schutzrichtlinie angibt. Der `-protectnow` Die Option ist nur für Data ONTAP 7-Mode gültig. Die Option gibt an, dass das Backup sofort auf dem sekundären Storage geschützt ist.

* `*-retain { -hourly | -daily | -weekly | -monthly | -unlimited}*`
+
Gibt an, ob das Backup stündlich, täglich, wöchentlich, monatlich oder unbegrenzt aufbewahrt werden soll. Wenn der `-retain` Die Option ist nicht angegeben, die Aufbewahrungsklasse ist standardmäßig auf `-hourly` Option. Um Backups für immer aufzubewahren, verwenden Sie den `-unlimited` Option. Der `-unlimited` Option macht das Backup nicht zur Löschung durch die Aufbewahrungsrichtlinie.

* `*-archivelogs*` *Option*
+
Erstellt Backup für Archivprotokolle

* `*-backup-dest _path1_, [, _[path2]_]*`
+
Gibt die Ziele für das Archivprotokoll an, die für die Sicherung des Archivprotokolls gesichert werden sollen.

* `*-exclude-dest _path1_, [, _[path2]_]*`
+
Gibt die Ziele für das Archivprotokoll an, die vom Backup ausgeschlossen werden sollen.

* `*-prunelogs {-all | -until-scnuntil-scn | -until-date _yyyy-MM-dd:HH:mm:ss_ | -before {-months | -days | -weeks | -hours}*`
+
Löscht die Archivprotokolldateien aus den Zielen des Archivprotokolls basierend auf den bei der Erstellung eines Backups bereitgestellten Optionen. Der `-all` Mit dieser Option werden alle Archivprotokolldateien aus den Speicherprotokollzielen gelöscht. Der `-until-scn` Mit dieser Option werden die Archivprotokolldateien bis zu einer angegebenen Systemänderungsnummer (SCN) gelöscht. Der `-until-date` Mit dieser Option werden die Archivprotokolldateien bis zum angegebenen Zeitraum gelöscht. Der `-before` Mit dieser Option werden die Archivprotokolldateien vor dem angegebenen Zeitraum gelöscht (Tage, Monate, Wochen, Stunden).

* `*-prune-dest _prune_dest1,prune_dest2_*`
+
Löscht die Archivprotokolldateien aus den Archivprotokollzielen, während die Sicherung erstellt wird.

* `*-taskspec _taskspec_*`
+
Gibt die XML-Datei für die Aufgabenspezifikation an, die für die Vorverarbeitung oder Nachverarbeitung des Backup-Vorgangs verwendet werden kann. Der vollständige Pfad der XML-Datei sollte zur Verfügung gestellt werden, während die Option -taskSpec angegeben wird.

* `*-dump*` *Option*
+
Sammelt die Speicherauszugsdateien nach einem erfolgreichen oder fehlgeschlagenen Datenbanksicherungvorgang.



'''


== Beispielbefehl

Mit dem folgenden Befehl wird ein vollständiges Online Backup erstellt, ein Backup auf dem Sekundärspeicher erstellt und die Aufbewahrungsrichtlinie auf einen täglichen Routineaufgaben setzt:

[listing]
----
smsap backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----
'''