---
permalink: unix-administration/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credentials, user, access, resource, secure, host, repositories, repository, database, profile, snapmanager, run, password, smsap 
summary: Mit diesem Befehl können Sie die Anmeldeinformationen für Benutzer festlegen, die auf sichere Ressourcen wie Hosts, Repositorys und Datenbankprofile zugreifen können. Das Hostpasswort ist das Passwort des Benutzers auf dem Host, auf dem SnapManager ausgeführt wird. Das Repository-Kennwort ist das Kennwort des Oracle-Benutzers, der das SnapManager-Repository-Schema enthält. Das Profilkennwort ist ein Passwort, das von der Person, die das Profil erstellt, gebildet wird. Wenn bei den Host- und Repository-Optionen die Option optional -password nicht enthalten ist, werden Sie aufgefordert, ein Kennwort des in den Befehlsargumenten angegebenen Typs einzugeben. 
---
= Der Befehl smsap Anmeldeinformationssatz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl können Sie die Anmeldeinformationen für Benutzer festlegen, die auf sichere Ressourcen wie Hosts, Repositorys und Datenbankprofile zugreifen können. Das Host-Passwort ist das Passwort des Benutzers auf dem Host, auf dem SnapManager ausgeführt wird. Das Repository-Kennwort ist das Kennwort des Oracle-Benutzers, der das SnapManager-Repository-Schema enthält. Das Profilkennwort ist ein Passwort, das von der Person, die das Profil erstellt, gebildet wird. Für die Host- und Repository-Optionen, falls optional `-password` Option ist nicht enthalten. Sie werden aufgefordert, ein Passwort des in den Befehlsargumenten angegebenen Typs einzugeben.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap credential set
[-host
-name _host_name_
-username _username_\]
[-password _password_\] \] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_\] [-password _repo_password_\] \]
-port _repo_port_ |
[-profile
-name _profile_name_\]
[-password _password_\] \]
[-quiet | -verbose]]
----


== Parameter

* `*-host _hostname_*`
+
Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem SnapManager ausgeführt wird.

+
Der `-host` Parameter enthält die folgenden Optionen:

+
** `-name _host_name_`: Gibt den Namen des Hosts an, für den Sie das Passwort festlegen möchten.
** `-username _user_name_`: Gibt den Benutzernamen auf dem Host an.
** `-password _password_` Gibt das Kennwort des Benutzers auf dem Host an.


* `*-repository -dbname*`
+
Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

+
Der `-repository` Parameter enthält die folgenden Optionen:

+
** `-dbname _repo_service_name_`: Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.
** `-host _repo_host_`: Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem die Repository-Datenbank ausgeführt wird.
** `-login-username _repo_username_`: Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank benötigt wird, in der das Repository gespeichert ist.
** `-password _password_`: Gibt das Kennwort an, das für den Zugriff auf die Datenbank benötigt wird, in der das Repository gespeichert ist.
** `-port _repo_port_`: Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.


* `*-profile -name _profile_name_*`
+
Gibt das Profil an, mit dem die Datenbank verknüpft ist.

+
Der `-profile` Parameter enthält die folgende Option:

+
** `-name _profilename_`: Gibt den Namen des Profils an, für das Sie das Passwort festlegen.
** `-password _password_`: Gibt das Passwort an, das für den Zugriff auf das Profil erforderlich ist.


* `*-quiet*`
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* `*-verbose*`
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.



'''


== Beispielbefehl zum Festlegen von Repository-Anmeldedaten

Im folgenden Beispiel werden Anmeldeinformationen für ein Repository festgelegt.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----
'''
'''


== Beispiel-Befehl zum Festlegen von Host-Anmeldedaten

Da eine Hostanmeldeinformationen eine tatsächliche Betriebssystemanmeldeinformationen darstellen, muss sie zusätzlich zum Passwort den Benutzernamen enthalten.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
'''