---
permalink: unix-administration/reference-the-smosmsapclone-list-command.html 
sidebar: sidebar 
keywords: command, list, clone, database, profile, smsap 
summary: Dieser Befehl listet die Klone der Datenbank für ein bestimmtes Profil auf. 
---
= Der Befehl smsap Clone list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieser Befehl listet die Klone der Datenbank für ein bestimmtes Profil auf.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap clone list
-profile _profile_name_
-delimiter _character_
[-quiet | -verbose]
----


== Parameter

* ``*-profile _profile_name_*``
+
Gibt die Liste der mit dem Profil verknüpften Klone an. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* ``*-delimiter _character_*``
+
Wenn dieser Parameter angegeben wird, führt der Befehl die Attribute in jeder Zeile durch das angegebene Zeichen getrennt auf.

* ``*-quiet*``
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* ``*-verbose*``
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.



'''


== Beispielbefehl

Im folgenden Beispiel werden die Datenbankklone im SALES1-Profil aufgeführt.

[listing]
----
smsap clone list -profile SALES1 -verbose
----
[listing]
----
ID Status SID Host Label Comment
-------- ------- ----- ------- ---------- -------
8ab...01 SUCCESS hsdbc server1 back1clone test comment
----
'''