---
permalink: unix-administration/reference-the-smo-notification-removesummarynotification-command.html 
sidebar: sidebar 
keywords: command, disable, summary, notification, profile, repository, database, smsap, remove-summary-notification 
summary: Mit diesem Befehl wird die Überblickbenachrichtigung für mehrere Profile in einer Repository-Datenbank deaktiviert. 
---
= Der Befehl smsap notification remove-summary-notification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl wird die Überblickbenachrichtigung für mehrere Profile in einer Repository-Datenbank deaktiviert.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap notification remove-summary-notification
-repository
-dbname _repo_service_name_
-port _repo_port_
-host _repo_host_
-login -username _repo_username_
[-quiet | -verbose]]
----


== Parameter

* `*-repository*`
+
Die folgenden Optionen `-repository` Geben Sie die Details der Datenbank für das Repository an.

* `*-port _repo_port_*`
+
Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.

* `*-dbname _repo_service_name_*`
+
Gibt den Namen der Datenbank an, in der das Repository gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

* `*-host _repo_host_*`
+
Gibt den Namen oder die IP-Adresse des Hostcomputers an, auf dem die Repository-Datenbank ausgeführt wird.

* `*-login _repo_username_*`
+
Gibt den Anmeldenamen an, der für den Zugriff auf die Datenbank, in der das Repository gespeichert ist, erforderlich ist.

* `*-quiet*`
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* `*-verbose*`
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.



'''
Im folgenden Beispiel wird die Überblickbenachrichtigung für mehrere Profile in einer Repository-Datenbank deaktiviert.

[listing, subs="+macros"]
----
pass:quotes[smsap notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login -username oba5]
----
'''