---
permalink: unix-administration/reference-troubleshooting-snapdrive-issues.html 
sidebar: sidebar 
keywords: common, issue, snapmanager, snapdrive, troubleshooting, product 
summary: Es gibt einige häufige Probleme, auf die Sie bei der Verwendung von SnapManager mit SnapDrive Produkten laufen könnten. 
---
= Fehlerbehebung bei SnapDrive-Problemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt einige häufige Probleme, auf die Sie bei der Verwendung von SnapManager mit SnapDrive Produkten laufen könnten.

Zunächst müssen Sie feststellen, ob das Problem mit SnapManager for SAP oder SnapDrive zusammenhängt. Wenn es sich um einen SnapDrive-Fehler handelt, zeigt SnapManager für SAP eine Fehlermeldung ähnlich wie:

[listing]
----
SMSAP-12111: Error executing snapdrive command "<snapdrive command>": <snapdrive error>
----
Im Folgenden finden Sie ein Beispiel für eine SnapDrive-Fehlermeldung `SMSAP-12111` Ist die Fehlernummer des SnapManager. Der `0001-770` Das Nummerierungsschema stellt SnapDrive für UNIX-Fehler dar.

[listing]
----
SMSAP-12111: Error executing snapdrive command
"/usr/sbin/snapdrive snap restore -file
/mnt/pathname/ar_anzio_name_10gR2_arrac1/data/undotbs02.dbf -snapname pathname.company.com:
/vol/ar_anzio_name_10gR2_arrac1:
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0": 0001-770
Admin error: Inconsistent number of files returned when listing contents of
/vol/ar_anzio_name_10gR2_arrac1/.snapshot/
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0/data
on filer pathname.
----
Im Folgenden finden Sie die häufigsten Fehlermeldungen von SnapDrive für UNIX in Bezug auf LUN-Erkennung, Konfigurationsprobleme und Speicherplatz. Wenn Sie einen dieser Fehler erhalten, lesen Sie das Kapitel Fehlerbehebung im Installationshandbuch für _SnapDrive_.

[cols="3a,1a"]
|===
| Symptom | Erklärung 


 a| 
``0001-136 Admin error: Unable to log on to filer: <filer> Please set user name and/or password for <filer>``
 a| 
Erstkonfiguration von SnapDrive



 a| 
`0001-382 Admin error: Multipathing rescan failed`
 a| 
Fehler bei der LUN-Erkennung



 a| 
`0001-462 Admin error: Failed to unconfigure multipathing for <LUN>: spd5: cannot stop device. Device busy.`
 a| 
Fehler bei der LUN-Erkennung



 a| 
``0001-476 Admin error: Unable to discover the device associated with ... 0001-710 Admin error: OS refresh of LUN failed ...``
 a| 
Fehler bei der LUN-Erkennung



 a| 
``0001-680 Admin error: Host OS requires an update to internal data to allow LUN creation or connection. Use 'snapdrive config prepare luns' or update this information manually...``
 a| 
Fehler bei der LUN-Erkennung



 a| 
`0001-817 Admin error: Failed to create volume clone ... : FlexClone not licensed`
 a| 
Erstkonfiguration von SnapDrive



 a| 
``0001-878 Admin error: HBA assistant not found. Commands involving LUNs should fail.``
 a| 
Fehler bei der LUN-Erkennung

|===