---
permalink: unix-administration/reference-where-to-go-for-more-information.html 
sidebar: sidebar 
keywords: information, basic, task, install, snapmanager, where, to, go 
summary: Hier finden Sie Informationen zu den grundlegenden Aufgaben, die bei der Installation und Verwendung von SnapManager anfallen. 
---
= Weitere Informationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hier finden Sie Informationen zu den grundlegenden Aufgaben, die bei der Installation und Verwendung von SnapManager anfallen.

[cols="2a,3a"]
|===
| Dokument An | Beschreibung 


 a| 
Beschreibungsseite „SnapManager“
 a| 
Auf dieser Seite finden Sie Informationen über SnapManager, Verweise auf Online-Dokumentationen und einen Link zur SnapManager Download-Seite, von der aus Sie die Software herunterladen können.



 a| 
_Data ONTAP-SAN-Konfigurationsleitfaden für 7-Mode_
 a| 
Dieses Dokument ist unter verfügbar http://mysupport.netapp.com/["NetApp Support"^].

Es handelt sich um ein dynamisches Online-Dokument mit aktuellsten Informationen zu den Anforderungen für das Einrichten eines Systems in einer SAN-Umgebung. Er liefert die aktuellen Details zu Storage-Systemen und Host-Plattformen, Verkabelungsproblemen, Switch-Problemen und Konfigurationen.



 a| 
Kompatibilitätsmatrix für SnapManager und SnapDrive
 a| 
Dieses Dokument ist im Abschnitt Interoperabilität verfügbar unter http://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool"^].

Es handelt sich um ein dynamisches Online-Dokument, das die aktuellsten Informationen enthält, die für SnapManager und seine Plattformanforderungen spezifisch sind.



 a| 
Versionshinweise zu SnapManager
 a| 
Dieses Dokument ist mit SnapManager erhältlich. Sie können auch eine Kopie von herunterladen http://mysupport.netapp.com/["NetApp Support"^].

Es enthält alle Last-Minute-Informationen, damit die Konfiguration reibungslos ausgeführt werden kann.



 a| 
Dokumentation von NetApp Host-Anschluss und Support-Kits
 a| 
http://mysupport.netapp.com/["NetApp Support"^].



 a| 
Informationen zu Host-Betriebssystem und Datenbank
 a| 
Diese Dokumente enthalten Informationen zu Ihrem Host-Betriebssystem und Ihrer Datenbanksoftware.

|===