---
permalink: unix-administration/reference-the-smosmsap-repository-rollingback-command.html 
sidebar: sidebar 
keywords: command, enable, roll, back, revert, version, snapmanager, original, version, upgrade, smsap, repository, rollback 
summary: Mit diesem Befehl können Sie ein Rollback bzw. ein Wechsel von einer höheren Version von SnapManager zu der Originalversion, von der Sie ein Upgrade durchgeführt haben, durchführen. 
---
= Der Befehl smsap Repository Rollback
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl können Sie ein Rollback bzw. ein Wechsel von einer höheren Version von SnapManager zu der Originalversion, von der Sie ein Upgrade durchgeführt haben, durchführen.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap repository rollback
-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_
-rollbackhost _host_with_target_database_
[-force]]
[-quiet | -verbose]
----


== Parameter

* `*-repository*`
+
Die Optionen, die dem -Repository folgen, geben die Details der Datenbank für das Repository an.

* `*-dbname _repo_service_name_*`
+
Gibt den Namen der Datenbank an, in der das Repository gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

* `*-host _repo_host_*`
+
Gibt den Namen oder die IP-Adresse des Hostcomputers an, auf dem die Repository-Datenbank ausgeführt wird.

* `*-login*`
+
Startet die Repository-Anmeldedaten.

* `*-username _repo_username_*`
+
Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank erforderlich ist, in der das Repository gespeichert ist.

* `*-rollbackhost _host_with_target_database_*`
+
Gibt den Namen des Hosts an, der von einer höheren Version von SnapManager auf die ursprüngliche niedrigere Version zurückgesetzt wird.

* `*-port _repo_port_*`
+
Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.

* `*-force*`
+
Versucht, die Aktualisierung des Repositorys zu erzwingen. SnapManager fordert Sie auf, vor der Aktualisierung eine Sicherung des aktuellen Repository durchzuführen.

* `*-noprompt*`
+
Zeigt die Eingabeaufforderung nicht an, bevor die Repository-Datenbank aktualisiert wird. Mit der Option -noprompt wird sichergestellt, dass die Eingabeaufforderung nicht angezeigt wird. Dies erleichtert die Aktualisierung von Repositorys mithilfe eines Skripts.

* `*-quiet*`
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* `*-verbose*`
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.



'''


== Beispielbefehl

Das folgende Beispiel aktualisiert das Repository in der SALESDB-Datenbank.

[listing]
----
smsap repository rollback -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -rollbackhost hostA
----
'''