---
permalink: unix-administration/reference-the-smosmsapbackup-restore-command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, recover, information, smsap 
summary: Sie können den Befehl Backup Restore ausführen, um Backups einer Datenbank oder eines Teils einer Datenbank wiederherzustellen, und optional die Datenbankinformationen wiederherstellen. 
---
= Der Befehl smsap Backup Restore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ausführen `backup restore` Befehl zum Wiederherstellen von Backups einer Datenbank oder eines Teils einer Datenbank und dann optional Wiederherstellen der Datenbankinformationen.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[smsap backup restore
-profile _profile_name_
[-label _label_ | -id _id_\]
[-files files [_files..._\] |
-tablespaces _tablespaces [tablespaces...\]_\] |
-complete | -controlfiles\]
[-recover {-alllogs | -nologs | -until _until_} [-using-backup-controlfile\] \]
[-restorespec _restorespec_ | -from-secondary [-temp-volume _temp_volume_\] [-copy-id _id_\]\]
[-preview\]
[-fast {-require | -override | -fallback | -off}\]
[-recover-from-location _path1_ [_, path2_\]\] [-taskspec _taskspec_\][-dump\]
[-force\]
[-quiet | -verbose\]]
----


== Parameter

* `*-profile _profile_name_*`
+
Gibt die Datenbank an, die wiederhergestellt werden soll. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* `*-label _name_*`
+
Stellt das Backup mit dem angegebenen Etikett wieder her.

* `*-id _guid_*`
+
Stellt die Sicherung mit der angegebenen GUID wieder her. Die GUID wird von SnapManager beim Erstellen eines Backups generiert. Sie können den Befehl smsap Backup list verwenden, um die GUID für jedes Backup anzuzeigen.

* *Wählen Sie alle oder bestimmte Dateien*
+
Optional können Sie eine der folgenden Optionen verwenden:

+
** `-complete` Stellt alle Datendateien im Backup wieder her.
** `-tablespaces _list_`: Stellt nur die angegebenen Tabellen aus dem Backup wieder her.
+
Sie müssen Leerzeichen verwenden, um die Namen in der Liste zu trennen.

** `-files _list_`: Stellt nur die angegebenen Dateien aus der Sicherung wieder her.
+
Sie müssen Leerzeichen verwenden, um die Namen in der Liste zu trennen. Wenn die Datenbank ausgeführt wird, stellt SnapManager sicher, dass der Tablespace, der die Dateien enthält, offline ist.



* `*-controlfiles*`
+
Stellt die Kontrolldateien wieder her. SnapManager ermöglicht Ihnen, in einem einzigen Vorgang Kontrolldateien zusammen mit den Datendateien aus den Backups wiederherzustellen. Der `-controlfiles` Die Option ist unabhängig von anderen Parametern für den Wiederherstellungsumfang, wie z. B. -`complete`, `-tablespaces`, und `-files`.

* `*-recover*`
+
Stellt die Datenbank nach der Wiederherstellung wieder her. Sie müssen auch den Punkt angeben, an dem SnapManager die Datenbank wiederherstellen soll, indem Sie eine der folgenden Optionen verwenden:

+
** `-nologs`: Stellt die Datenbank zum Zeitpunkt der Sicherung wieder her und wendet keine Logs an.
+
Sie können diesen Parameter für Online- oder Offline-Backups verwenden.

** `-alllogs`: Stellt die Datenbank auf die letzte Transaktion oder Commit wieder her und wendet alle erforderlichen Protokolle an.
** `-until date`: Stellt die Datenbank bis zum angegebenen Datum und der angegebenen Zeit wieder her.
+
Sie müssen das Jahr-Monat-Datum verwenden: Stunde: Minute: Sekunde (_yyyy-mm-dd:hh:mm:ss_) Format. Verwenden Sie für Stunden je nach Datenbankeinstellung entweder das 12-Stunden- oder das 24-Stunden-Format.

** `-until scn`: Rolls leiten die Datendateien weiter, bis sie die angegebene Systemändernummer (SCN) erreicht.
** `-using-backup-controlfile`: Stellt die Datenbank mit der Backup-Kontrolldatei wieder her.


* `*-restorespec*`
+
Ermöglicht Ihnen, die Daten in einem aktiven File-System wiederherzustellen und aus den angegebenen Daten wiederherzustellen, indem Sie jede Original-Snapshot-Kopie einem aktiven File-System zuweisen. Falls Sie keine Option angeben, werden die Daten aus den Snapshot Kopien im primären Storage von SnapManager wiederhergestellt. Sie können eine der folgenden Optionen angeben:

+
** `-restorespec`: Gibt die wiederherzustellenden Daten und das Wiederherstellungsformat an.
** `-from-secondary`: Stellt die Daten aus dem sekundären Speicher wieder her.
+
Diese Option kann nicht verwendet werden, wenn das Backup im Primär-Storage vorhanden ist. Das primäre Backup muss freigegeben werden, bevor ein Backup aus dem sekundären Storage wiederhergestellt werden kann. Wenn Sie ein temporäres Volume verwenden, müssen Sie das Volume mithilfe der angeben `-temp-volume` Option.

+
Sie müssen das angeben `-copy-id` Wenn Sie die Option angeben `-from-secondary` Option. Wenn sich mehrere Backups auf dem sekundären Speichersystem befinden, wird der angezeigt `-copy-id` Die Option wird verwendet, um anzugeben, welche Backup-Kopie auf dem sekundären Speicher für den Wiederherstellungsvorgang verwendet werden soll.

+

NOTE: Wenn Sie Data ONTAP in 7-Mode verwenden, müssen Sie einen gültigen Wert für das angeben `-copy-id` Option. Wenn Sie jedoch Clustered Data ONTAP verwenden, bietet Ihnen das `-copy-id` Option ist nicht erforderlich

+
Bei der Wiederherstellung aus dem Sekundärspeicher versucht SnapManager zunächst, Daten direkt aus dem sekundären Speichersystem auf das primäre Speichersystem (ohne Beteiligung des Hosts) wiederherzustellen. Wenn SnapManager diese Art der Wiederherstellung nicht durchführen kann (z. B. wenn die Dateien nicht Teil des Dateisystems sind), dann wird SnapManager zurück zu einer Host-seitigen Dateikopie zurückkehren. SnapManager verfügt über zwei Methoden zur Wiederherstellung einer Host-seitigen Dateikopie aus dem sekundären Server. Die von SnapManager gewählte Methode wird im konfiguriert `smsap.config` Datei:

** Direkt: SnapManager klont die Daten auf sekundärem Storage, mountet die geklonten Daten vom sekundären Storage-System auf den Host und kopiert sie dann Daten aus dem Klon in die aktive Umgebung.
+
Dies ist die standardmäßige sekundäre Zugriffsrichtlinie.

** Indirekt: SnapManager kopiert die Daten zunächst auf ein temporäres Volume im Primärspeicher, bindet die Daten vom temporären Volume an den Host und kopiert dann Daten aus dem temporären Volume in die aktive Umgebung.
+
Diese Richtlinie sollte nur verwendet werden, wenn der Host keinen direkten Zugriff auf das sekundäre Speichersystem hat. Wiederherstellungen mit der indirekten Methode dauern doppelt so lange wie die Richtlinien für direkte sekundäre Zugriffe, da zwei Kopien der Daten erstellt werden.



+
Die Entscheidung, ob die direkte oder indirekte Methode verwendet werden soll, wird durch den Wert des gesteuert `_restore.secondaryAccessPolicy_` Parameter in `smsap.config` Konfigurationsdatei

* `*-preview*`
+
Zeigt die folgenden Informationen an:

+
** Welcher Wiederherstellungsmechanismus (schnelle Wiederherstellung, Filesystem-Wiederherstellung auf Storage-Seite, Dateiwiederherstellung auf Storage-Seite oder Wiederherstellung von Host-seitigen Dateikopien) wird zum Wiederherstellen jeder Datei verwendet
** Warum effizientere Mechanismen nicht verwendet wurden, um jede Datei wiederherzustellen, wenn Sie die angeben `-verbose` Option Wenn Sie die verwenden `-preview` Diese Option muss Folgendes wissen:
** Der `-force` Die Option hat keine Auswirkung auf den Befehl.
** Der `-recover` Die Option hat keine Auswirkung auf den Befehl.
** Der `-fast` Option (`-require, -override, -fallback,` Oder `-off`) Hat erhebliche Auswirkungen auf die Ausgabe. Um eine Vorschau des Wiederherstellungsvorgangs anzuzeigen, muss die Datenbank gemountet werden. Wenn Sie eine Vorschau eines Wiederherstellungsplans anzeigen möchten und die Datenbank derzeit nicht angehängt ist, mountet SnapManager die Datenbank. Wenn die Datenbank nicht angehängt werden kann, schlägt der Befehl fehl, und SnapManager gibt die Datenbank in ihren ursprünglichen Status zurück.


+
Der `-preview` Mit der Option werden bis zu 20 Dateien angezeigt. Sie können die maximale Anzahl von Dateien konfigurieren, die im angezeigt werden sollen `smsap.config` Datei:

* `*-fast*`
+
Ermöglicht Ihnen die Auswahl des Prozesses, den Sie für den Wiederherstellungsvorgang verwenden möchten. Zudem kann SnapManager die Verwendung des Volume-basierten schnellen Wiederherstellungsprozesses anstelle anderer Wiederherstellungsverfahren erzwingen, wenn alle obligatorischen Bedingungen für die Wiederherstellung erfüllt sind. Falls bekannt ist, dass eine Wiederherstellung eines Volumes nicht möglich ist, kann dieser Vorgang ebenfalls durchgeführt werden, um SnapManager die Überprüfung der Berechtigung und die Wiederherstellung mithilfe des schnellen Restore-Vorgangs zu verhindern.

+
Der `-fast` Die Option umfasst die folgenden Parameter:

+
** `-require`: Ermöglicht es Ihnen, SnapManager zu zwingen, eine Volume-Wiederherstellung durchzuführen, wenn alle Bedingungen für die Wiederherstellung erfüllt sind.
+
Wenn Sie den angeben `-fast` Option, geben Sie für keinen Parameter an `-fast`, SnapManager verwendet das `-require` Standardparameter.

** `-override`: Ermöglicht es Ihnen, die nicht obligatorischen Eignungsüberprüfungen zu überschreiben und den volumenbasierten schnellen Wiederherstellungsprozess durchzuführen.
** `-fallback`: Ermöglicht Ihnen die Wiederherstellung der Datenbank mit jeder Methode, die SnapManager bestimmt.
+
Wenn Sie den nicht angeben `-fast` Option, SnapManager verwendet die Standardeinstellung `backup restore -fast fallback` Option.

** `-off`: Ermöglicht es Ihnen, die Zeit zu vermeiden, die für die Durchführung von Eignungskontrollen erforderlich ist.


* `*-recover-from-location*`
+
Gibt den externen Speicherort der Archivprotokolldateien an. SnapManager nimmt die Archivprotokolldateien vom externen Standort auf und verwendet diese für den Recovery-Prozess.

* `*-taskspec*`
+
Gibt die XML-Datei für die Aufgabenspezifikation für die Vorverarbeitung oder Nachbearbeitung des Wiederherstellungsvorgangs an. Sie müssen den vollständigen Pfad der XML-Datei für die Aufgabenspezifikation angeben.

* `*-dump*`
+
Gibt an, die Speicherauszugsdateien nach dem Wiederherstellungsvorgang zu sammeln.

* `*-force*`
+
Ändert ggf. den Datenbankstatus in einen niedrigeren Status als der aktuelle Status. Für Real Application Clusters (RAC) müssen Sie das angeben `-force` Option, wenn SnapManager den Status einer beliebigen RAC-Instanz in einen niedrigeren Status ändern muss.

+
Standardmäßig kann SnapManager den Datenbankstatus während eines Vorgangs in einen höheren Status ändern. Diese Option ist nicht erforderlich, damit SnapManager die Datenbank in einen höheren Status ändert.

* `*-quiet*`
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* `*-verbose*`
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an. Sie können diese Option verwenden, um zu sehen, warum effizientere Wiederherstellungsprozesse nicht verwendet werden konnten, um die Datei wiederherzustellen.



'''


== Beispiel

Im folgenden Beispiel wird eine Datenbank zusammen mit den Kontrolldateien wiederhergestellt:

[listing]
----
smsap backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----
'''