---
permalink: unix-administration/reference-the-smosmsaprepository-show-command.html 
sidebar: sidebar 
keywords: command, display, information, repository, smsap 
summary: Mit diesem Befehl werden Informationen zum Repository angezeigt. 
---
= Der Befehl smsap Repository show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl werden Informationen zum Repository angezeigt.



== Syntax

[listing]
----
smsap repository show
-repository
-dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
[-quiet | -verbose]
----


== Parameter

* ``*-repository*``
+
Die folgenden Optionen `-repository` Geben Sie die Details der Datenbank für das Repository an.

* ``*-dbname _repo_service_name_*``
+
Gibt den Namen der Datenbank an, in der das Repository gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

* ``*-host _repo_host_*``
+
Gibt den Namen oder die IP-Adresse des Hostcomputers an, auf dem die Repository-Datenbank ausgeführt wird.

* ``*-login*``
+
Startet die Repository-Anmeldedaten.

* ``*-username _repo_username_*``
+
Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank erforderlich ist, in der das Repository gespeichert ist.

* ``*-port repo_port*``
+
Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.

* ``*-quiet*``
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* ``*-verbose*``
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Befehlsbeispiel

Das folgende Beispiel zeigt Details zum Repository in der SALESDB-Datenbank.

[listing]
----
smsap repository show -repository -dbname SALESDB  -host server1
-port 1521 -login -username admin
Repository Definition:
User Name: admin
Host Name: server1
Database Name: SALESDB
Database Port: 1521
Version: 28
Hosts that have run operations using this repository: 2
server2
server3
Profiles defined in this repository: 2
GSF5A
GSF3A
Incomplete Operations: 0
----