---
permalink: unix-administration/task-protect-archive-log-backups.html 
sidebar: sidebar 
keywords: create, creating, profile, enable, protection, archive, log, backup, policy, protect 
summary: Während der Erstellung von Profilen können Sie den Schutz für die Backups des Archivprotokolls basierend auf der Schutzrichtlinie für Archivprotokolle aktivieren. 
---
= Sicherung von Backups für Archivprotokolle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Während der Erstellung von Profilen können Sie den Schutz für die Backups des Archivprotokolls basierend auf der Schutzrichtlinie für Archivprotokolle aktivieren.

.Schritt
. Geben Sie den folgenden Befehl ein:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_dbname_ -host _repo_host_ -port _repo_port_ -login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] [-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-separate-archivelog-backups-retain-archivelog-backups-hours _hours_ | -days _days_ | -weeks _weeks_ | -months _months_ [-protect [-protection-policy _policy_name_] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
[cols="2a,5a"]
|===
| Wenn... | Dann... 


 a| 
*Sie wollen Archiv-Log-Backups separat sichern und die Archiv-Log-Dateien schützen*
 a| 
Legen Sie die folgenden Optionen fest:

** `-separate-archivelog-backups` Ermöglicht Ihnen, die Archivprotokolldateien von den Datendateien zu trennen.
** `-protect` Weist eine separate Schutzrichtlinie für die Archiv-Log-Backups des Archivprotokolls zu.
** `-protection-policy` Weist die Schutzrichtlinie für die Backup des Archivprotokolls zu.


|===

