---
permalink: unix-administration/task-customize-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, customizing 
summary: Sie können den E-Mail-Betreff für das neue Profil anpassen, wenn Sie es erstellen. 
---
= Passen Sie den E-Mail-Betreff für ein neues Profil an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den E-Mail-Betreff für das neue Profil anpassen, wenn Sie es erstellen.

Sie können den Betreff der E-Mail mithilfe des \{profile}_\{Operation-Name}_\{db-sid}_\{db-Host}_\{Startdatum}_\{Enddatum}_\{Status}-Musters anpassen oder Ihren eigenen Text eingeben.

[cols="1a,3a,2a"]
|===
| Variablenname | Beschreibung | Beispielwert 


 a| 
`_profile_`
 a| 
Profilname, der für den Datenbankvorgang verwendet wird
 a| 
PROF1



 a| 
`_operation-name_`
 a| 
Name des Datenbankvorgangs
 a| 
Backup, Daten-Backup, Daten- und Archivprotokolle Backup



 a| 
`_db-sid_`
 a| 
SID der Datenbank
 a| 
DB1



 a| 
`_db-host_`
 a| 
Name des Hostservers
 a| 
Hosta



 a| 
`_start-date_`
 a| 
Startzeit der Datenbankoperation im Format mmdd:hh:ss yyyy
 a| 
April 27 21:00:45 PST 2012



 a| 
`_end-date_`
 a| 
Endzeit des Datenbankvorgangs im Format mmdd:hh:ss yyyy
 a| 
April 27 21:10:45 PST 2012



 a| 
`_status_`
 a| 
Status des Datenbankvorgangs
 a| 
Erfolg

|===
Wenn Sie keinen Wert für die Variablen angeben, zeigt SnapManager die folgende Fehlermeldung an: `Missing value(s) -subject.`

. Geben Sie den folgenden Befehl ein:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -portrepo_port-login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] [-notification [-success -email _email_address1,email_address2_ -subject _subject_pattern_] [-failure -email _email_address1,email_address2_ -subject _subject_pattern_]]*`



'''
Das folgende Beispiel zeigt das Muster des E-Mail-Betreff:

[listing]
----

smsap profile create -profile sales1 -profile-password admin1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username admin2 -database -dbname DB1 -host 10.72.197.142 -sid DB1
-osaccount oracle -osgroup dba -profile-notification -success -email admin@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----
'''