---
permalink: unix-administration/task-create-restore-specifications.html 
sidebar: sidebar 
keywords: restore, specification, file, xml, original, alternate, location, file, restore, snapmanager, specification, location, creating, create 
summary: Die Spezifikationsdatei für die Wiederherstellung ist eine XML-Datei, die die ursprünglichen und alternativen Speicherorte enthält, aus denen die Datei wiederhergestellt werden kann. SnapManager verwendet diese Spezifikationsdatei, um Dateien vom angegebenen Speicherort wiederherzustellen. 
---
= Erstellen von Wiederherstellungsspezifikationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Spezifikationsdatei für die Wiederherstellung ist eine XML-Datei, die die ursprünglichen und alternativen Speicherorte enthält, aus denen die Datei wiederhergestellt werden kann. SnapManager verwendet diese Spezifikationsdatei, um Dateien vom angegebenen Speicherort wiederherzustellen.

*Über diese Aufgabe*

Sie können die Wiederherstellungsspezifikationsdatei mit einem beliebigen Texteditor erstellen. Sie müssen eine .XML-Erweiterung für die Datei verwenden.

.Schritte
. Öffnen Sie eine Textdatei.
. Geben Sie Folgendes ein:
+
`*<restore-specification xmlns="http://www.netapp.com">*`

. Geben Sie alle Informationen zur Dateizuordnung unter Verwendung des im folgenden Beispiel gezeigten Formats ein:
+
[listing]
----
<file-mapping>
    <original-location>/path/dbfilename.dbf</original-location>
    <alternate-location>/path/dbfilename1.dbf</alternate-location>
</file-mapping>
----
+
Die Dateizuordnung gibt an, aus welcher Datei wiederhergestellt wird. Der ursprüngliche Speicherort ist der Speicherort der Datei auf dem aktiven Dateisystem zum Zeitpunkt der Sicherung. Der alternative Speicherort ist der Speicherort, von dem die Datei wiederhergestellt wird.

. Geben Sie alle Informationen zur Dateisystemzuordnung unter Verwendung des im Beispiel gezeigten Formats ein:
+
[listing]
----
<mountpoint-mapping>
     <original-location>/path/db_name</original-location>
     <snapname>snapname</snapname>
     <alternate-location>/path/vaultlocation</alternate-location>
</mountpoint-mapping>
<mountpoint-mapping>
     <original-location>+DiskGroup_1</original-location>
     <snapname>snapname</snapname>
     <alternate-location>+DiskGroup_2</alternate-location>
</mountpoint-mapping>
----
+
Der Mountpunkt bezieht sich auf den Verzeichnispfad `/mnt/myfs/`). Die Mountpunkt-Mapping-Zuordnung gibt den Bereitstellungspunkt an, aus dem die Dateien wiederhergestellt werden. Der ursprüngliche Speicherort ist der Speicherort des Mountpoint im aktiven File-System zum Zeitpunkt des Backups. Der alternative Speicherort ist der Bereitstellungspunkt, aus dem die Dateien im ursprünglichen Speicherort wiederhergestellt werden. Der `_snapname_` Ist der Name der Snapshot Kopie, in der die Originaldateien gesichert wurden.

+

NOTE: Der Name einer Snapshot Kopie ist eine notwendige Komponente, da dasselbe Filesystem in einem einzelnen Backup-Vorgang mehrfach eingesetzt werden kann (z. B. einmal für die Datendateien und einmal für die Protokolle).

. Geben Sie die Tags und Standorte für die RAW-Gerätezuordnung mithilfe des im Beispiel gezeigten Formats ein:
+
[listing]
----
<raw-device-mapping>
     <original-location>/path/raw_device_name</original-location>
     <alternate-location>/path/raw_device_name</alternate-location>
</raw-device-mapping>
----
+
RAW Device Mapping gibt den Speicherort an, von dem ein RAW-Gerät wiederhergestellt wird.

. Geben Sie Folgendes ein:
+
`*</restore-specification>*`

. Speichern Sie die Datei als .XML-Datei und schließen Sie die Spezifikation.




== Beispiel für die Wiederherstellung der Spezifikation

Das folgende Beispiel zeigt die Struktur der wiederherstellenden Spezifikationen:

[listing]
----
<?xml version="1.0" encoding="UTF-8"?>
<restore-specification xmlns="http://www.netapp.com">
<!-- "Restore from file(s)" -->
     <file-mapping>
          <original-location>/mnt/pathname/dbname/users01.dbf</original-location>
          <alternate-location>/mnt/vault/users01.dbf</alternate-location>
     </file-mapping>
<!-- "Restore from host mounted file system(s)" -->
     <mountpoint-mapping>
          <original-location>/mnt/pathname/dbname/fs</original-location>
          <snapname>Snapshotname</snapname>
          <alternate-location>/mnt/vaultlocation</alternate-location>
     </mountpoint-mapping>
<!-- "Restore from raw device" -->
     <raw-device-mapping>
          <original-location>/pathname/devicename</original-location>
          <alternate-location>/pathname/devicename</alternate-location>
     </raw-device-mapping>
</restore-specification>
----