---
permalink: unix-administration/task-configure-summary-e-mail-notification-for-multiple-profiles.html 
sidebar: sidebar 
keywords: snapmanager, enable, configure, summary, email, notification, multiple, profile, repository, database, configuring 
summary: Mit SnapManager können Sie eine E-Mail-Benachrichtigung für mehrere Profile unter einer Repository-Datenbank konfigurieren. 
---
= Konfigurieren Sie eine zusammenfassende E-Mail-Benachrichtigung für mehrere Profile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapManager können Sie eine E-Mail-Benachrichtigung für mehrere Profile unter einer Repository-Datenbank konfigurieren.

*Über diese Aufgabe*

Sie können den SnapManager-Server-Host als Benachrichtigungs-Host festlegen, von dem aus die zusammenfassende Benachrichtigung E-Mail an die Empfänger gesendet wird. Wenn der Hostname oder die IP-Adresse des SnapManager-Servers geändert wird, kann auch der Benachrichtigungs-Host aktualisiert werden.

Sie können eine der Zeitplanzeiten auswählen, zu denen Sie eine E-Mail-Benachrichtigung benötigen:

* Stündlich: Um jede Stunde eine E-Mail-Benachrichtigung zu erhalten
* Täglich: Um täglich eine E-Mail-Benachrichtigung zu erhalten
* Wöchentlich: Um wöchentlich eine E-Mail-Benachrichtigung zu erhalten
* Monatlich: Um monatlich eine E-Mail-Benachrichtigung zu erhalten


Sie müssen eine einzelne E-Mail-Adresse oder eine kommagetrennte Liste von E-Mail-Adressen eingeben, um Benachrichtigungen für Vorgänge zu erhalten, die mit diesen Profilen durchgeführt werden. Wenn Sie mehrere E-Mail-Adressen eingeben, müssen Sie sicherstellen, dass zwischen Komma und der nächsten E-Mail-Adresse kein Leerzeichen vorhanden ist.

SnapManager ermöglicht Ihnen das Hinzufügen eines benutzerdefinierten E-Mail-Betreff unter Verwendung der folgenden Variablen:

* Profilname, der für den Datenbankvorgang verwendet wird.
* Datenbankname
* SID der Datenbank
* Name des Hostservers
* Startzeit des Datenbankvorgangs im Format yyyymmdd:hh:ss
* Endzeit des Datenbankvorgangs im Format yyyyymmdd:hh:ss
* Status des Datenbankvorgangs


Wenn Sie kein angepasstes Thema hinzufügen möchten, zeigt SnapManager eine Fehlermeldung an: `Missing value -subject`.

. Geben Sie den folgenden Befehl ein:
+
`*smsap notification update-summary-notification -repository -port _repo_port_ -dbname _repo_service_name_ -host _repo_host_ -login-username _repo_username_ -email _email_address1,email_address2_ -subject _subject-pattern_ -frequency {-daily-time _daily_time_ | -hourly-time _hourly_time_ | -monthly-time _monthly_time_ -date {1 |2...|31} | -weekly-time _weekly_time_ -day {1 |2 |3 |4 |5 |6 |7}} -profiles _profile1 profile2_ -notification-host _notification-host_*`

+
Weitere Optionen für diesen Befehl:

+
``[-force] [-noprompt]``

+
``[-quiet | -verbose]``



'''
[listing]
----

smsap notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email-address admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1 -notification-host wales
----
'''