---
permalink: unix-administration/task-split-a-clone-on-a-primary-or-secondary-storage.html 
sidebar: sidebar 
keywords: clone, split, complete, metadata, remove, repository, primary, secondary, storage, delete, free 
summary: Sie können den Klon mit dem Befehl „Clone Split“ teilen. Nach Abschluss der Klonabteilung werden die Klonmetadaten aus der Repository-Datenbank entfernt und das mit dem Klon verbundene Backup kann gelöscht oder freigegeben werden. 
---
= Teilen Sie einen Klon auf Primär- oder Sekundär-Storage auf
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das verwenden `clone split` Befehl zum Aufteilen des Klons. Nach Abschluss der Klonabteilung werden die Klonmetadaten aus der Repository-Datenbank entfernt und das mit dem Klon verbundene Backup kann gelöscht oder freigegeben werden.

*Über diese Aufgabe*

Das neue Profil, das nach dem erfolgreichen Split-Vorgang erstellt wurde, wird zum Verwalten des Split-Klons verwendet. Das neue Profil wird wie jedes andere bestehende Profil in SnapManager sein. Mit diesem Profil können Backup-, Wiederherstellungs- und Klonvorgänge durchgeführt werden.

Außerdem können Sie die E-Mail-Benachrichtigung für das neue Profil konfigurieren. Dadurch kann der Datenbankadministrator über den Status des Datenbankvorgangs benachrichtigt werden, der mit dem Profil durchgeführt wurde.


NOTE: SnapManager unterstützt die Abtrennung, wenn sie nur auf einem FlexClone durchgeführt wird.

Wenn der Split-Vorgang fehlschlägt, wird eine entsprechende Fehlermeldung mit dem Grund für einen Fehler angezeigt. Der Status mehrerer Vorgänge wird auch im Betriebsprotokoll angezeigt. Beispiel:

[listing]
----
--[ INFO] The following operations were completed:
Clone Split : Success
Profile Create : Failed
Clone Detach : Success
----
Optional können Sie die Dump-Dateien nach einem erfolgreichen oder fehlgeschlagenen Klon-Split-Vorgang sammeln.


NOTE: Nach der Eingabe des `clone split` Befehl, Sie sollten den SnapManager-Server nicht beenden, bis der Klonabtrennvorgang gestartet wurde.


NOTE: SnapManager generiert das Profil, auch wenn Sie keinen Wert für das Oracle Konto angeben (osccount und osgroup).

.Schritt
. Geben Sie den folgenden Befehl ein:
+
`*smsap clone split -profile _clone-profile_ -host _hostname_ [-label _clone-label_ | -id _clone-id_]-split-label _split-operation-label_ -comment _comment_ new-profile _new-profile-name_ [-profile-password _new-profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count _n_] [-duration _m_]]] [-profile-comment _profile-comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] | [-noprotect]][-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-quiet | -verbose]-dump*`


