---
permalink: unix-administration/task-configure-snapdrive-when-rbac-is-not-enabled.html 
sidebar: sidebar 
keywords: register, root, user, administrator, datafabric, manager, server, storage, system, snapdrive, data, protection, configuring, configure, rbac 
summary: Sie müssen den Root-Benutzer oder den Administrator des DataFabric Manager Servers und den Root-Benutzer des Storage-Systems mit SnapDrive registrieren, um die Datensicherung zu ermöglichen. 
---
= Konfigurieren Sie SnapDrive, wenn die rollenbasierte Zugriffssteuerung nicht aktiviert ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen den Root-Benutzer oder den Administrator des DataFabric Manager Servers und den Root-Benutzer des Storage-Systems mit SnapDrive registrieren, um die Datensicherung zu ermöglichen.

.Schritte
. Geben Sie den folgenden Befehl ein, um den DataFabric Manager-Server zu aktualisieren, um die Änderungen direkt auf dem Storage-System durch die Zieldatenbank zu aktualisieren:
+
*Beispiel*

+
`*dfm host discover _storage_system_*`

. Geben Sie den folgenden Befehl ein, um den Root-Benutzer oder den Administrator des DataFabric Manager Servers mit SnapDrive zu registrieren:
+
*Beispiel*

+
`*snapdrive config set -dfm _Administratordfm_host_*`

. Geben Sie den folgenden Befehl ein, um den Root-Benutzer oder den Administrator des Speichersystems mit SnapDrive zu registrieren:
+
*Beispiel*

+
`*snapdrive config set root _storage_system_*`


