---
permalink: unix-administration/task-remove-history-configuration-associated-with-a-single-profile-or-multiple-profiles.html 
sidebar: sidebar 
keywords: snapmanager, enable, remove, history, setting, operation, purge, information, associate, single, multiple, profile, removing 
summary: Mit SnapManager können Sie die Verlaufseinstellungen eines SnapManager-Vorgangs entfernen. Mit diesem Vorgang werden alle Verlaufsdaten gelöscht, die mit einem einzelnen Profil oder mehreren Profilen verknüpft sind. 
---
= Entfernen Sie die Verlaufseinstellungen, die einem einzelnen Profil oder mehreren Profilen zugeordnet sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapManager können Sie die Verlaufseinstellungen eines SnapManager-Vorgangs entfernen. Mit diesem Vorgang werden alle Verlaufsdaten gelöscht, die mit einem einzelnen Profil oder mehreren Profilen verknüpft sind.

.Schritt
. Um den Verlauf der SnapManager Vorgänge zu entfernen, die mit einem einzelnen Profil oder mehreren Profilen verknüpft sind, geben Sie den folgenden Befehl ein:
+
`*smsap history remove -profile {_-name, profile_name [profile_name1, profile_name2_] | all-repository-login [-password _repo_password_] -username _repo_username_ -dbname _repo_dbname_ -host _repo_host_ -port _repo_port_} -operation {-operations _operation_name_ [_operation_name1, operation_name2_] | -all} [-quiet | -verbose]*`


