---
permalink: unix-administration/task-configure-snapdrive-when-rbac-is-enabled.html 
sidebar: sidebar 
keywords: role-based, access, control, rbac, enable, configure, datafabric, manager, server, capability, capabilities, snapdrive, create, storage, system, regiser, configure, configuring 
summary: Wenn die rollenbasierte Zugriffssteuerung aktiviert ist, müssen Sie den DataFabric Manager Server so konfigurieren, dass die RBAC-Funktionen enthalten sind. Sie müssen auch den im DataFabric Manager Server erstellten SnapDrive-Benutzer und den Root-Benutzer des Storage-Systems in SnapDrive registrieren. 
---
= Konfigurieren Sie DataFabric Manager Server und SnapDrive, wenn die RBAC aktiviert ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die rollenbasierte Zugriffssteuerung aktiviert ist, müssen Sie den DataFabric Manager Server so konfigurieren, dass die RBAC-Funktionen enthalten sind. Sie müssen auch den im DataFabric Manager Server erstellten SnapDrive-Benutzer und den Root-Benutzer des Storage-Systems in SnapDrive registrieren.

.Schritte
. Konfigurieren Sie den DataFabric Manager Server.
+
.. Geben Sie den folgenden Befehl ein, um den DataFabric Manager-Server zu aktualisieren, um die Änderungen direkt auf dem Storage-System durch die Zieldatenbank zu aktualisieren:
+
`*dfm host discover _storage_system_*`

.. Erstellen Sie einen neuen Benutzer im DataFabric Manager-Server, und legen Sie das Passwort fest.
.. Geben Sie den folgenden Befehl ein, um den Betriebssystembenutzer zur DataFabric Manager Server-Administratorliste hinzuzufügen:
+
`*dfm user add _sd-admin_*`

.. Geben Sie den folgenden Befehl ein, um eine neue Rolle im DataFabric Manager-Server zu erstellen:
+
`*dfm role create _sd-admin-role_*`

.. Geben Sie den folgenden Befehl ein, um die Funktion DFM.Core.AccessCheck Global zur Rolle hinzuzufügen:
+
`*dfm role add _sd-admin-role_ DFM.Core.AccessCheck Global*`

.. Hinzufügen `sd-admin-role` Geben Sie zum Benutzer des Betriebssystems den folgenden Befehl ein:
+
`*dfm user role set _sd-adminsd-admin-role_*`

.. Geben Sie den folgenden Befehl ein, um eine weitere Rolle im DataFabric Manager-Server für den SnapDrive-Root-Benutzer zu erstellen:
+
`*dfm role create _sd-protect_*`

.. Um der für den SnapDrive-Root-Benutzer oder den Administrator erstellten Rolle RBAC-Funktionen hinzuzufügen, geben Sie die folgenden Befehle ein:
+
`*dfm role add _sd-protect_ SD.Config.Read Global*`

+
`*dfm role add _sd-protect_ SD.Config.Write Global*`

+
`*dfm role add _sd-protect_ SD.Config.Delete Global*`

+
`*dfm role add _sd-protect_ SD.Storage.Read Global*`

+
`*dfm role add _sd-protect_ DFM.Database.Write Global*`

+
`*dfm role add _sd-protect_ GlobalDataProtection*`

.. Geben Sie den folgenden Befehl ein, um den oracle-Zieldatenbank zur Liste der Administratoren im DataFabric Manager Server hinzuzufügen und die sd-Protect-Rolle zu zuweisen:
+
`*dfm user add -r _sd-protecttardb_host1_\oracle*`

.. Geben Sie den folgenden Befehl ein, um das Storage-System hinzuzufügen, das von der Zieldatenbank im DataFabric Manager Server verwendet wird:
+
`*dfm host set _storage_system_ hostLogin=oracle hostPassword=_password_*`

.. Geben Sie den folgenden Befehl ein, um eine neue Rolle in dem Storage-System zu erstellen, das von der Zieldatenbank auf dem DataFabric Manager-Server verwendet wird:
+
`*dfm host role create -h _storage_system-c_ "api-**,login-*" _storage-rbac-role_**`

.. Geben Sie den folgenden Befehl ein, um eine neue Gruppe im Storage-System zu erstellen und die neue Rolle zuzuweisen, die im DataFabric Manager-Server erstellt wurde:
+
`*dfm host usergroup create -h _storage_system_-r _storage-rbac-rolestorage-rbac-group_*`

.. Geben Sie den folgenden Befehl ein, um einen neuen Benutzer im Storage-System zu erstellen und die neue Rolle und die im DataFabric Manager-Server erstellte Gruppe zuzuweisen:
+
`*dfm host user create -h _storage_system_-r _storage-rbac-role_ -p _password_ -g _storage-rbac-grouptardb_host1_*`



. Konfigurieren Sie SnapDrive.
+
.. So registrieren Sie die Anmeldeinformationen des `_sd-admin_` Benutzer mit SnapDrive, geben Sie den folgenden Befehl ein:
+
`*snapdrive config set -dfm _sd-admindfm_host_*`

.. Geben Sie den folgenden Befehl ein, um den Root-Benutzer oder den Administrator des Speichersystems mit SnapDrive zu registrieren:
+
`*snapdrive config set _tardb_host1storage_system_*`




