---
permalink: unix-administration/task-restore-backups-from-an-alternate-location.html 
sidebar: sidebar 
keywords: restore, backup, alternate, location, data, file, intermediate, system, block, raw, device, restoring 
summary: Sie können Backups von einem alternativen Speicherort wiederherstellen, um die Datendateien von einem zwischengeschalteten Dateisystem in ein aktives Dateisystem wiederherzustellen oder die Datenblöcke von einem Zwischenrohgerät in ein aktives RAW-Gerät wiederherzustellen. 
---
= Wiederherstellung von Backups von einem alternativen Speicherort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Backups von einem alternativen Speicherort wiederherstellen, um die Datendateien von einem zwischengeschalteten Dateisystem in ein aktives Dateisystem wiederherzustellen oder die Datenblöcke von einem Zwischenrohgerät in ein aktives RAW-Gerät wiederherzustellen.

*Was Sie brauchen*

* Erstellen Sie eine XML-Datei für die Wiederherstellungsspezifikation, und geben Sie den Typ der Wiederherstellungsmethode an, die Sie verwenden möchten.


*Über diese Aufgabe*

Sie können den smsap benutzen `backup restore` Geben Sie den Befehl und die XML-Datei für die Wiederherstellungsspezifikation an, die Sie erstellt haben, um das Backup von einem anderen Speicherort wiederherzustellen.

. Geben Sie den folgenden Befehl ein:
+
`*smsap backup restore -profile _profile_ -label _label_ -complete -alllogs -restorespec _restorespec_*`


