---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: SnapManager for SAP Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/reference-releasenotes.html"
  - section: unix-installation-cmode
  - section: unix-installation-7mode
  - section: unix-administration
  - section: windows
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Produktübersicht
      url: "/unix-installation-cmode/reference-smsap-isg-product-overview.html"
    - title: Versionshinweise
      url: reference-releasenotes.html
  - title: Administration
    links:
    - title: SnapManager für UNIX wird konfiguriert
      url: "/unix-administration/concept-configuring-snapmanager-for-oraclesap.html"
    - title: Konfigurieren von SnapManager für Windows
      url: "/windows/concept-configuring-snapmanager-for-oraclesap.html"
  - title: Installation und Einrichtung
    links:
    - title: Implementierungs-Workflow (7-Mode)
      url: "/unix-installation-7mode/reference-smsap-isg-deployment-workflow.html"
    - title: Implementierungs-Workflow (Cluster-Mode)
      url: "/unix-installation-cmode/reference-smsap-isg-deployment-workflow.html"
  - title: Mehr Ressourcen
    links:
    - title: NetApp Support
      url: https://mysupport.netapp.com/site/global/dashboard
    - title: NetApp Communitys
      url: https://community.netapp.com/
