---
permalink: unix-installation-cmode/task-perform-rolling-upgrade-on-a-single-host-or-multiple-hosts.html 
sidebar: sidebar 
keywords: perform, roll, upgrade, single, multiple, snapmanager, server, host, command-line, interface, cli, manage 
summary: 'Sie können Rolling Upgrades für einen einzelnen oder mehrere SnapManager Server Hosts über die Befehlszeilenschnittstelle (CLI) durchführen. Der aktualisierte SnapManager-Server-Host wird dann nur mit der späteren Version von SnapManager verwaltet.' 
---
= Führen Sie Rolling Upgrade auf einem einzelnen oder mehreren Hosts durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Rolling Upgrades für einen einzelnen oder mehrere SnapManager Server Hosts über die Befehlszeilenschnittstelle (CLI) durchführen. Der aktualisierte SnapManager-Server-Host wird dann nur mit der späteren Version von SnapManager verwaltet.



== Was Sie benötigen

Sie müssen sicherstellen, dass alle Voraussetzungen für das Durchführen eines Rolling Upgrades abgeschlossen sind.

.Schritte
. Geben Sie den folgenden Befehl ein, um ein Rolling Upgrade auf einem einzelnen Host durchzuführen: `*smsap repository rollingupgrade -repository-dbname _repo_service_name_ -host _repo_host_ -login -username _repo_username_ -port _repo_port_ -upgradehost _host_with_target_database_ -force [-quiet | -verbose]*`
+
*Beispiel*

+
Der folgende Befehl führt das Rolling Upgrade aller auf HostA eingebundenen Zieldatenbanken und einer Repository-Datenbank namens repoA auf repo_Host durch:

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA
----
. Geben Sie den folgenden Befehl ein, um ein Rolling Upgrade auf mehreren Hosts durchzuführen: `*smsap repository rollingupgrade -repository -dbname _repo_service_name_ -host _repo_host_ -login -username _repo_username_ -port _repo_port_ -upgradehost _host_with_target_database1_,_host_with_target_database2_ -force [-quiet | -verbose]*`
+

NOTE: Geben Sie bei mehreren Hosts die durch Komma getrennten Hostnamen ein, und stellen Sie sicher, dass Sie keinen Speicherplatz zwischen dem Komma und dem nächsten Hostnamen angeben.Wenn Sie eine RAC-Konfiguration (Real Application Clusters) verwenden, müssen Sie alle RAC-verbundenen Hosts manuell aktualisieren. Verwenden Sie können `-allhosts` So führen Sie das Rolling Upgrade aller Hosts durch.

+
*Beispiel*

+
Der folgende Befehl führt das Rolling Upgrade aller auf den Hosts eingebundenen Zieldatenbanken, hostA und hostB sowie einer Repository-Datenbank namens repoA auf repo_Host durch:

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA,hostB
----
. Um ein Rolling Upgrade auf allen Hosts einer Repository-Datenbank durchzuführen, geben Sie den folgenden Befehl ein:
+
`*smsap repository rollingupgrade -repository -dbname _repo_service_name_ -host _repo_host_ -login -username _repo_username_ -port _repo_port_ -allhosts -force [-quiet | -verbose]*`

+
Nachdem Sie die Repository-Datenbank erfolgreich aktualisiert haben, können Sie alle SnapManager-Vorgänge auf der Zieldatenbank ausführen.

+
*Beispiel*

+
Der folgende Befehl führt das Rolling Upgrade aller Zieldatenbanken durch, die in einer Repository-Datenbank mit dem Namen „repoA“ auf repo_Host verfügbar sind:

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
      -allhosts
----




== Nachdem Sie fertig sind

* Wenn der SnapManager-Server automatisch startet, müssen Sie den Server neu starten, um sicherzustellen, dass Sie die Zeitpläne anzeigen können.
* Wenn Sie einen der beiden zugehörigen Hosts aktualisieren, müssen Sie nach dem ersten Upgrade des zweiten Hosts ein Upgrade durchführen.
+
Wenn Sie beispielsweise einen Klon von Host A nach Host B erstellt oder ein Backup von Host A an Host B angehängt haben, hängen die Hosts A und B miteinander zusammen. Wenn Sie Host A aktualisieren, wird eine Warnmeldung angezeigt, in der Sie aufgefordert werden, den Host B bald nach dem Upgrade von Host A zu aktualisieren

+

NOTE: Die Warnmeldungen werden angezeigt, obwohl der Klon gelöscht wurde oder das Backup während des Rolling Upgrades von Host A von Host B abgehängt wurde Dies liegt daran, dass Metadaten im Repository für die Vorgänge vorhanden sind, die auf dem Remote-Host durchgeführt werden.


